module.exports = {
  apps: [
    {
      name: "pawn-dev-6002",
      cwd: "./apps/api/backend",
      script: "src/server.js",
      interpreter: "node",
      interpreter_args: "--env-file=.env.development",
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "5s",
      env: {
        NODE_ENV: "development",
        APP_ENV: "development",
        PORT: "6002",
        PAWN_PORT: "6002",
        HOST: "0.0.0.0",
      },
    },
    {
      name: "pawn-staging-6003",
      cwd: "./apps/api/backend",
      script: "src/server.js",
      interpreter: "node",
      interpreter_args: "--env-file=.env.staging",
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "5s",
      env: {
        NODE_ENV: "staging",
        APP_ENV: "staging",
        PORT: "6003",
        PAWN_PORT: "6003",
        HOST: "0.0.0.0",
      },
    },
    {
      name: "pawn-prod-6001",
      cwd: "./apps/api/backend",
      script: "src/server.js",
      interpreter: "node",
      interpreter_args: "--env-file=.env.production",
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "5s",
      env: {
        NODE_ENV: "production",
        APP_ENV: "production",
        PORT: "6001",
        PAWN_PORT: "6001",
        HOST: "0.0.0.0",
      },
    },
  ],
};
