import { useEffect, useId, useRef, type ReactNode } from "react";
import "../../styles/super-admin-operations-v2.css";

export function OperationsHeader({ eyebrow = "Super Admin", title, description, actions, updatedAt }: { eyebrow?: string; title: string; description: string; actions?: ReactNode; updatedAt?: Date | null }) {
  return <header className="ops-header"><div><p className="ops-eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p>{updatedAt ? <LastUpdated value={updatedAt} /> : null}</div>{actions ? <div className="ops-toolbar">{actions}</div> : null}</header>;
}
export function MetricCard({ label, value, description, status }: { label: string; value: ReactNode; description?: string; status?: string }) { return <article className="ops-metric"><div className="ops-metric__head"><span>{label}</span>{status ? <StatusBadge value={status} /> : null}</div><strong>{value}</strong>{description ? <p>{description}</p> : null}</article>; }
export function StatusBadge({ value }: { value: string }) { const key = value.toLowerCase().replaceAll("_", "-"); return <span className={`ops-status ops-status--${key}`}>{value.replaceAll("_", " ")}</span>; }
export function Toolbar({ children, label = "Page controls" }: { children: ReactNode; label?: string }) { return <div className="ops-toolbar" role="group" aria-label={label}>{children}</div>; }
export function FilterPanel({ children, title = "Filters" }: { children: ReactNode; title?: string }) { const id = useId(); return <section className="ops-panel ops-filter" aria-labelledby={id}><h2 id={id}>{title}</h2><div className="ops-filter__grid">{children}</div></section>; }
export function LoadingState({ label = "Loading operations data…", rows = 3 }: { label?: string; rows?: number }) { return <div className="ops-state" role="status" aria-live="polite"><span className="sr-only">{label}</span>{Array.from({ length: rows }, (_, index) => <span className="ops-skeleton" key={index} />)}</div>; }
export function EmptyState({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <div className="ops-state"><h3>{title}</h3><p>{description}</p>{action}</div>; }
export function ErrorState({ message, onRetry }: { message: string; onRetry?: () => void }) { return <div className="ops-state ops-state--error" role="alert"><h3>Unable to load this view</h3><p>{message}</p>{onRetry ? <button className="btn btn-secondary" onClick={onRetry}>Try again</button> : null}</div>; }
export function LastUpdated({ value }: { value: Date | string }) { const date = value instanceof Date ? value : new Date(value); return <span className="ops-updated">Last updated <time dateTime={date.toISOString()}>{date.toLocaleString()}</time></span>; }
export function DetailDrawer({ open, title, onClose, children }: { open: boolean; title: string; onClose: () => void; children: ReactNode }) { const titleId = useId(); const closeRef = useRef<HTMLButtonElement>(null); useEffect(() => { if (open) closeRef.current?.focus(); }, [open]); if (!open) return null; return <div className="ops-overlay" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><aside className="ops-drawer" role="dialog" aria-modal="true" aria-labelledby={titleId} onKeyDown={(event) => { if (event.key === "Escape") onClose(); }}><div className="ops-drawer__head"><h2 id={titleId}>{title}</h2><button ref={closeRef} className="btn btn-secondary" onClick={onClose} aria-label={`Close ${title}`}>Close</button></div>{children}</aside></div>; }
export type ConfirmationSpec = { action: string; target: string; impact: string; highRisk?: boolean; confirmText?: string };
export function ConfirmationDialog({ spec, reason, confirmation, busy = false, onReasonChange, onConfirmationChange, onCancel, onConfirm }: { spec: ConfirmationSpec | null; reason: string; confirmation: string; busy?: boolean; onReasonChange: (value: string) => void; onConfirmationChange: (value: string) => void; onCancel: () => void; onConfirm: () => void }) { const titleId = useId(); const reasonId = useId(); const requiredText = spec?.confirmText || "CONFIRM"; if (!spec) return null; const valid = reason.trim().length >= 8 && (!spec.highRisk || confirmation === requiredText); return <div className="ops-overlay"><section className="ops-dialog" role="alertdialog" aria-modal="true" aria-labelledby={titleId} onKeyDown={(event) => { if (event.key === "Escape" && !busy) onCancel(); }}><p className="ops-eyebrow">Administrative confirmation</p><h2 id={titleId}>{spec.action}</h2><dl><dt>Target</dt><dd>{spec.target}</dd><dt>Impact</dt><dd>{spec.impact}</dd></dl><label htmlFor={reasonId}>Required reason<textarea id={reasonId} autoFocus required minLength={8} value={reason} onChange={(event) => onReasonChange(event.target.value)} placeholder="Explain the operational need (at least 8 characters)" /></label>{spec.highRisk ? <label>Type <strong>{requiredText}</strong> to continue<input value={confirmation} onChange={(event) => onConfirmationChange(event.target.value)} autoComplete="off" /></label> : null}<div className="ops-dialog__actions"><button className="btn btn-secondary" onClick={onCancel} disabled={busy}>Cancel</button><button className="btn btn-primary" onClick={onConfirm} disabled={!valid || busy}>{busy ? "Working…" : "Confirm action"}</button></div></section></div>; }
