import type { OwnerApplicationUpdate } from "../services/ownerApplications";
import { BUSINESS_TYPES, COUNTRIES, regionsFor, type FieldErrors } from "../utils/ownerApplicationFields";

type Props = { value: OwnerApplicationUpdate; errors: FieldErrors; customBusinessType: string; legacyBusinessType: string; disabled?: boolean; onChange: (value: OwnerApplicationUpdate) => void; onCustomBusinessTypeChange: (value: string) => void; onCountryChange: (country: string) => void };
function FieldError({ name, errors }: { name: string; errors: FieldErrors }) { return errors[name] ? <span className="field-error" id={`${name}-error`}>{errors[name]}</span> : null; }
const described = (errors: FieldErrors, key: string) => errors[key] ? `${key}-error` : undefined;

export default function OwnerApplicationFields({ value, errors, customBusinessType, legacyBusinessType, disabled, onChange, onCustomBusinessTypeChange, onCountryChange }: Props) {
  const address = value.businessAddress || { line1: "", line2: "", city: "", state: "", postalCode: "", country: "US" };
  const regions = regionsFor(address.country);
  const input = (key: keyof OwnerApplicationUpdate, next: string) => onChange({ ...value, [key]: next });
  const addressInput = (key: keyof typeof address, next: string) => onChange({ ...value, businessAddress: { ...address, [key]: next } });
  const field = (key: string) => ({ id: `owner-${key}`, name: key, "aria-invalid": !!errors[key], "aria-describedby": described(errors, key) });
  return <div className="owner-application__grid">
    <label htmlFor="owner-businessName"><span>Legal business name <strong>(Required)</strong></span><input {...field("businessName")} disabled={disabled} value={value.businessName || ""} onChange={e => input("businessName", e.target.value)} /><FieldError name="businessName" errors={errors} /></label>
    <label htmlFor="owner-businessType"><span>Business type <strong>(Required)</strong></span><select {...field("businessType")} disabled={disabled} value={value.businessType || ""} onChange={e => input("businessType", e.target.value)}><option value="">Select business type</option>{BUSINESS_TYPES.map(option => <option key={option} value={option}>{option}</option>)}<option value="Other">Other</option>{legacyBusinessType ? <option value={legacyBusinessType}>Legacy value: {legacyBusinessType}</option> : null}</select><FieldError name="businessType" errors={errors} /></label>
    {value.businessType === "Other" ? <label htmlFor="owner-businessTypeOther"><span>Other business type <strong>(Required)</strong></span><input {...field("businessTypeOther")} disabled={disabled} value={customBusinessType} onChange={e => onCustomBusinessTypeChange(e.target.value)} /><FieldError name="businessTypeOther" errors={errors} /></label> : null}
    <label htmlFor="owner-businessEmail"><span>Business email <strong>(Required)</strong></span><input {...field("businessEmail")} type="email" autoComplete="email" disabled={disabled} value={value.businessEmail || ""} onChange={e => input("businessEmail", e.target.value)} /><FieldError name="businessEmail" errors={errors} /></label>
    <label htmlFor="owner-businessPhone"><span>Business phone <em>(Optional)</em></span><input {...field("businessPhone")} type="tel" autoComplete="tel" inputMode="tel" disabled={disabled} value={value.businessPhone || ""} onChange={e => input("businessPhone", e.target.value)} /><FieldError name="businessPhone" errors={errors} /></label>
    <label htmlFor="owner-websiteUrl"><span>Website <em>(Optional)</em></span><input {...field("websiteUrl")} type="url" inputMode="url" placeholder="https://example.com" disabled={disabled} value={value.websiteUrl || ""} onChange={e => input("websiteUrl", e.target.value)} /><FieldError name="websiteUrl" errors={errors} /></label>
    <label htmlFor="owner-country"><span>Country <strong>(Required)</strong></span><select {...field("country")} autoComplete="country" disabled={disabled} value={address.country} onChange={e => onCountryChange(e.target.value)}><option value="">Select country</option>{COUNTRIES.map(([code, name]) => <option key={code} value={code}>{name}</option>)}{address.country && !COUNTRIES.some(([code]) => code === address.country) ? <option value={address.country}>Saved unsupported value: {address.country}</option> : null}</select><FieldError name="country" errors={errors} /></label>
    <label htmlFor="owner-line1"><span>Physical address <strong>(Required)</strong></span><input {...field("line1")} autoComplete="street-address" disabled={disabled} value={address.line1} onChange={e => addressInput("line1", e.target.value)} /><FieldError name="line1" errors={errors} /></label>
    <label htmlFor="owner-line2"><span>Address line 2 <em>(Optional)</em></span><input id="owner-line2" name="line2" disabled={disabled} value={address.line2 || ""} onChange={e => addressInput("line2", e.target.value)} /></label>
    <label htmlFor="owner-city"><span>City <strong>(Required)</strong></span><input {...field("city")} autoComplete="address-level2" disabled={disabled} value={address.city} onChange={e => addressInput("city", e.target.value)} /><FieldError name="city" errors={errors} /></label>
    <label htmlFor="owner-state"><span>State / region <strong>(Required)</strong></span>{regions.length ? <select {...field("state")} disabled={disabled} value={address.state} onChange={e => addressInput("state", e.target.value)}><option value="">Select state or region</option>{regions.map(([code, name]) => <option key={code} value={code}>{name}</option>)}{address.state && !regions.some(([code]) => code === address.state) ? <option value={address.state}>Saved value: {address.state}</option> : null}</select> : <input {...field("state")} disabled={disabled} value={address.state} onChange={e => addressInput("state", e.target.value)} />}<FieldError name="state" errors={errors} /></label>
    <label htmlFor="owner-postalCode"><span>Postal code <strong>(Required)</strong></span><input {...field("postalCode")} autoComplete="postal-code" disabled={disabled} value={address.postalCode} onChange={e => addressInput("postalCode", e.target.value)} /><FieldError name="postalCode" errors={errors} /></label>
    <label htmlFor="owner-licenseNumber"><span>License number <em>(Optional)</em></span><input {...field("licenseNumber")} disabled={disabled} value={value.licenseNumber || ""} onChange={e => input("licenseNumber", e.target.value)} /><FieldError name="licenseNumber" errors={errors} /></label>
    <label htmlFor="owner-licenseState"><span>License state / region <em>(Required with license)</em></span>{regions.length ? <select {...field("licenseState")} disabled={disabled} value={value.licenseState || ""} onChange={e => input("licenseState", e.target.value)}><option value="">Select issuing region</option>{regions.map(([code, name]) => <option key={code} value={code}>{name}</option>)}{value.licenseState && !regions.some(([code]) => code === value.licenseState) ? <option value={value.licenseState}>Saved value: {value.licenseState}</option> : null}</select> : <input {...field("licenseState")} disabled={disabled} value={value.licenseState || ""} onChange={e => input("licenseState", e.target.value)} />}<FieldError name="licenseState" errors={errors} /></label>
  </div>;
}
