/* eslint-disable react-hooks/static-components -- the local error renderer closes over this form's error map */
import type { OwnerApplicationUpdate } from "../services/ownerApplications";
import { BUSINESS_TYPES, COUNTRIES, regionsFor, type FieldErrors } from "../utils/ownerApplicationFields";

type Props = { value: OwnerApplicationUpdate; errors: FieldErrors; customBusinessType: string; disabled?: boolean; onChange: (value: OwnerApplicationUpdate) => void; onCustomBusinessTypeChange: (value: string) => void; onCountryChange: (country: string) => void };

export default function OwnerApplicationFields({ value, errors, customBusinessType, disabled, onChange, onCustomBusinessTypeChange, onCountryChange }: Props) {
  const address = value.businessAddress || { line1: "", line2: "", city: "", state: "", postalCode: "", country: "US" };
  const regions = regionsFor(address.country);
  const legacyType = value.businessType && value.businessType !== "Other" && !BUSINESS_TYPES.includes(value.businessType as typeof BUSINESS_TYPES[number]) ? value.businessType : "";
  const input = (key: keyof OwnerApplicationUpdate, next: string) => onChange({ ...value, [key]: next });
  const addressInput = (key: keyof typeof address, next: string) => onChange({ ...value, businessAddress: { ...address, [key]: next } });
  const described = (key: string) => errors[key] ? `${key}-error` : undefined;
  const ErrorText = ({ name }: { name: string }) => errors[name] ? <span className="field-error" id={`${name}-error`}>{errors[name]}</span> : null;
  return <div className="owner-application__grid">
    <label><span>Legal business name <strong>(Required)</strong></span><input disabled={disabled} value={value.businessName || ""} onChange={e => input("businessName", e.target.value)} aria-invalid={!!errors.businessName} aria-describedby={described("businessName")} /><ErrorText name="businessName" /></label>
    <label><span>Business type <strong>(Required)</strong></span><select disabled={disabled} value={value.businessType || ""} onChange={e => input("businessType", e.target.value)} aria-invalid={!!errors.businessType} aria-describedby={described("businessType")}><option value="">Select business type</option>{BUSINESS_TYPES.map(option => <option key={option}>{option}</option>)}<option value="Other">Other</option>{legacyType ? <option value={legacyType}>Legacy value: {legacyType}</option> : null}</select><ErrorText name="businessType" /></label>
    {value.businessType === "Other" ? <label><span>Other business type <strong>(Required)</strong></span><input disabled={disabled} value={customBusinessType} onChange={e => onCustomBusinessTypeChange(e.target.value)} aria-invalid={!!errors.businessTypeOther} aria-describedby={described("businessTypeOther")} /><ErrorText name="businessTypeOther" /></label> : null}
    <label><span>Business email <strong>(Required)</strong></span><input type="email" disabled={disabled} value={value.businessEmail || ""} onChange={e => input("businessEmail", e.target.value)} aria-invalid={!!errors.businessEmail} aria-describedby={described("businessEmail")} /><ErrorText name="businessEmail" /></label>
    <label><span>Business phone <em>(Optional)</em></span><input type="tel" autoComplete="tel" inputMode="tel" disabled={disabled} value={value.businessPhone || ""} onChange={e => input("businessPhone", e.target.value)} aria-invalid={!!errors.businessPhone} aria-describedby={described("businessPhone")} /><ErrorText name="businessPhone" /></label>
    <label><span>Website <em>(Optional)</em></span><input type="url" inputMode="url" placeholder="https://example.com" disabled={disabled} value={value.websiteUrl || ""} onChange={e => input("websiteUrl", e.target.value)} aria-invalid={!!errors.websiteUrl} aria-describedby={described("websiteUrl")} /><ErrorText name="websiteUrl" /></label>
    <label><span>Country <strong>(Required)</strong></span><input list="owner-country-options" autoComplete="country" disabled={disabled} value={address.country} onChange={e => onCountryChange(e.target.value.toUpperCase())} aria-invalid={!!errors.country} aria-describedby={described("country")} /><datalist id="owner-country-options">{COUNTRIES.map(([code, name]) => <option key={code} value={code}>{name}</option>)}</datalist><ErrorText name="country" /></label>
    <label><span>Physical address <strong>(Required)</strong></span><input autoComplete="street-address" disabled={disabled} value={address.line1} onChange={e => addressInput("line1", e.target.value)} aria-invalid={!!errors.line1} aria-describedby={described("line1")} /><ErrorText name="line1" /></label>
    <label><span>Address line 2 <em>(Optional)</em></span><input disabled={disabled} value={address.line2 || ""} onChange={e => addressInput("line2", e.target.value)} /></label>
    <label><span>City <strong>(Required)</strong></span><input autoComplete="address-level2" disabled={disabled} value={address.city} onChange={e => addressInput("city", e.target.value)} aria-invalid={!!errors.city} aria-describedby={described("city")} /><ErrorText name="city" /></label>
    <label><span>State / region <strong>(Required)</strong></span>{regions.length ? <select disabled={disabled} value={address.state} onChange={e => addressInput("state", e.target.value)} aria-invalid={!!errors.state} aria-describedby={described("state")}><option value="">Select state or region</option>{regions.map(([code, name]) => <option key={code} value={code}>{name}</option>)}{address.state && !regions.some(([code]) => code === address.state) ? <option value={address.state}>Saved value: {address.state}</option> : null}</select> : <input disabled={disabled} value={address.state} onChange={e => addressInput("state", e.target.value)} aria-invalid={!!errors.state} aria-describedby={described("state")} />}<ErrorText name="state" /></label>
    <label><span>Postal code <strong>(Required)</strong></span><input autoComplete="postal-code" disabled={disabled} value={address.postalCode} onChange={e => addressInput("postalCode", e.target.value)} aria-invalid={!!errors.postalCode} aria-describedby={described("postalCode")} /><ErrorText name="postalCode" /></label>
    <label><span>License number <em>(Optional)</em></span><input disabled={disabled} value={value.licenseNumber || ""} onChange={e => input("licenseNumber", e.target.value)} aria-invalid={!!errors.licenseNumber} aria-describedby={described("licenseNumber")} /><ErrorText name="licenseNumber" /></label>
    <label><span>License state / region <em>(Required with license)</em></span>{regions.length ? <select disabled={disabled} value={value.licenseState || ""} onChange={e => input("licenseState", e.target.value)} aria-invalid={!!errors.licenseState} aria-describedby={described("licenseState")}><option value="">Select issuing region</option>{regions.map(([code, name]) => <option key={code} value={code}>{name}</option>)}{value.licenseState && !regions.some(([code]) => code === value.licenseState) ? <option value={value.licenseState}>Saved value: {value.licenseState}</option> : null}</select> : <input disabled={disabled} value={value.licenseState || ""} onChange={e => input("licenseState", e.target.value)} aria-invalid={!!errors.licenseState} aria-describedby={described("licenseState")} />}<ErrorText name="licenseState" /></label>
  </div>;
}
