import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { acceptBuyerItemSubmissionOffer, getSubmissionComparisonDashboard, rejectBuyerItemSubmissionOffer, withdrawBuyerItemSubmission, type SubmissionComparisonDashboard } from "../services/buyerItemSubmissions";

export default function SubmissionComparisonDashboard({ submissionId }: { submissionId: string }) {
  const [dashboard, setDashboard] = useState<SubmissionComparisonDashboard | null>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState("");
  const load = useCallback(async (signal?: AbortSignal) => { try { setDashboard(await getSubmissionComparisonDashboard(submissionId, signal)); } catch (error) { if ((error as Error)?.name !== "AbortError") setMessage(error instanceof Error ? error.message : "Dashboard failed to load"); } }, [submissionId]);
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort(); }, [load]);
  async function action(key: string, work: () => Promise<unknown>) { setBusy(key); setMessage(""); try { await work(); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Action failed"); } finally { setBusy(""); } }
  if (!dashboard?.distributionMode) return null;
  return <section className="sellitem-next-card" aria-labelledby="comparison-title"><div className="sellitem-section-title"><span>Seller comparison</span><h2 id="comparison-title">Private shop responses</h2><p>{dashboard.title} · {dashboard.distributionMode}</p></div>
    <p>Marketplace: {dashboard.marketplaceListing?.status || "Not selected"}{dashboard.marketplaceListing?.expiresAt ? ` · expires ${new Date(dashboard.marketplaceListing.expiresAt).toLocaleDateString()}` : ""}</p>
    <div className="sellitem-flow-list">{dashboard.targets.map((target) => <div key={target.id}><strong>{target.shop.name}</strong><span>{target.status} · {target.shop.city}, {target.shop.state}</span><small>{target.unreadMessageCount} unread message{target.unreadMessageCount === 1 ? "" : "s"}</small>{target.offer ? <><span>${Number(target.offer.amount).toFixed(2)} · {target.offer.status}</span>{target.offer.message ? <small>{target.offer.message}</small> : null}{target.offer.status === "PENDING" ? <div className="sellitem-mini-actions"><button type="button" disabled={Boolean(busy)} onClick={() => void action(target.offer!.id, () => acceptBuyerItemSubmissionOffer(target.offer!.id))}>Accept</button><button type="button" disabled={Boolean(busy)} onClick={() => void action(target.offer!.id, () => rejectBuyerItemSubmissionOffer(target.offer!.id))}>Reject</button></div> : null}</> : <small>No monetary offer yet.</small>}{target.conversation ? <Link to={`/messages/${target.conversation.id}`}>Message shop</Link> : null}</div>)}</div>
    {!dashboard.closedAt && !dashboard.withdrawnAt ? <button type="button" disabled={Boolean(busy)} onClick={() => void action("withdraw", () => withdrawBuyerItemSubmission(submissionId))}>Withdraw opportunity</button> : null}{message ? <p role="status">{message}</p> : null}</section>;
}
