export const deployedSecretValues = [
  "synthetic-jwt-secret-at-least-thirty-two-characters",
  "synthetic-integration-key-at-least-thirty-two-characters",
  "sk_live_synthetic_never_real",
  "whsec_synthetic_platform_never_real",
  "whsec_synthetic_connect_never_real",
  "re_synthetic_never_real",
  "postgresql://synthetic:synthetic@prod-db.invalid/pawnloop",
];

export function validDeployedEnvironment(environment) {
  const production = environment === "production";
  return {
    APP_NAME: "pawnloop-api", APP_ENV: environment, NODE_ENV: environment,
    APP_VERSION: "git-0123456789abcdef", PORT: production ? "6001" : "6003",
    API_ORIGIN: production ? "https://api.pawnloop.invalid" : "https://api.staging.invalid",
    FRONTEND_URL: production ? "https://pawnloop.invalid" : "https://web.staging.invalid",
    WEB_URL: production ? "https://pawnloop.invalid" : "https://web.staging.invalid",
    CORS_ORIGIN: production ? "https://pawnloop.invalid" : "https://web.staging.invalid",
    CORS_ORIGINS: production ? "https://pawnloop.invalid,https://www.pawnloop.invalid" : "https://web.staging.invalid",
    DATABASE_URL: production ? deployedSecretValues[6] : "postgresql://synthetic:synthetic@staging-db.invalid/pawnloop_staging",
    PRODUCTION_DATABASE_HOST: production ? "prod-db.invalid" : undefined,
    STAGING_DATABASE_HOST: production ? undefined : "staging-db.invalid",
    JWT_SECRET: deployedSecretValues[0], INTEGRATION_CREDENTIAL_ENCRYPTION_KEY: deployedSecretValues[1],
    STRIPE_SECRET_KEY: production ? deployedSecretValues[2] : "sk_test_synthetic_never_real",
    STRIPE_PUBLISHABLE_KEY: production ? "pk_live_synthetic_never_real" : "pk_test_synthetic_never_real",
    STRIPE_WEBHOOK_SECRET: deployedSecretValues[3], STRIPE_CONNECT_ENABLED: "true",
    STRIPE_CONNECT_WEBHOOK_SECRET: deployedSecretValues[4], EMAIL_PROVIDER: "resend",
    EMAIL_FROM: "PawnLoop <no-reply@pawnloop.invalid>", RESEND_API_KEY: deployedSecretValues[5],
    RESEND_API_TIMEOUT_MS: "10000", TRUST_PROXY: "1",
    INVITE_ONLY_REGISTRATION_ENABLED: "true", AUTH_RATE_LIMIT_ENABLED: "true",
    AUTH_RATE_LIMIT_WINDOW_MS: "900000", AUTH_RATE_LIMIT_IP_MAX: "30",
    AUTH_RATE_LIMIT_SENSITIVE_IP_MAX: "10", AUTH_RATE_LIMIT_IDENTIFIER_MAX: "20",
    AUTH_RATE_LIMIT_COMBINED_MAX: "5", MFA_MODE: "disabled",
    REDIS_URL: "rediss://synthetic:synthetic@redis.invalid:6379",
    AUCTION_SCHEDULER_ENABLED: "false", AUCTION_SCHEDULER_INTERVAL_MS: "5000",
    AUCTION_SCHEDULER_BATCH_SIZE: "50", MARKETPLACE_RESERVATION_SCHEDULER_ENABLED: "false",
    MARKETPLACE_RESERVATION_SCHEDULER_INTERVAL_MS: "60000",
    MARKETPLACE_RESERVATION_SCHEDULER_BATCH_SIZE: "50",
    MARKETPLACE_RESERVATION_TTL_MINUTES: "30", SCHEDULER_OWNER: "disabled",
    READINESS_TIMEOUT_MS: "5000",
    DURABLE_UPLOADS_ENABLED: "true",
    UPLOAD_STORAGE_ENDPOINT: "https://object-storage.invalid",
    UPLOAD_STORAGE_REGION: "auto",
    UPLOAD_STORAGE_BUCKET: "pawnloop-assets",
    UPLOAD_STORAGE_ACCESS_KEY_ID: "synthetic-upload-access-key",
    UPLOAD_STORAGE_SECRET_ACCESS_KEY: "synthetic-upload-secret-key",
    UPLOAD_STORAGE_PUBLIC_BASE_URL: "https://assets.pawnloop.invalid",
    UPLOAD_STORAGE_FORCE_PATH_STYLE: "false",
    UPLOAD_MAX_FILE_BYTES: "10485760",
    UPLOAD_MAX_FILES: "10",
    UPLOAD_MAX_AGGREGATE_BYTES: "52428800",
    UPLOAD_MAX_WIDTH: "12000",
    UPLOAD_MAX_HEIGHT: "12000",
    UPLOAD_MAX_PIXELS: "40000000",
    UPLOAD_RATE_LIMIT_WINDOW_MS: "60000",
    UPLOAD_RATE_LIMIT_USER_MAX: "20",
    UPLOAD_RATE_LIMIT_IP_MAX: "60",
    UPLOAD_MAX_CONCURRENT: "1",
    UPLOAD_STORAGE_TIMEOUT_MS: "10000",
  };
}
