import { useEffect, useState } from "react";
import AdminPageShell from "../components/AdminPageShell";
import { adminApi, type GovernanceLookupRow, type UserGovernanceDetail } from "../services/adminApi";

const actions = ["SUSPEND_ACCOUNT", "RESTORE_ACCOUNT", "RESTRICT_MESSAGING", "RESTORE_MESSAGING", "DISABLE_SHOP_CONTACT", "RESTORE_SHOP_CONTACT", "RESTRICT_DISCOVERABILITY", "RESTORE_DISCOVERABILITY"];
export default function SuperAdminGovernancePage() {
  const [query, setQuery] = useState(""); const [type, setType] = useState<"PUBLIC" | "EMAIL" | "INTERNAL_ID">("PUBLIC");
  const [rows, setRows] = useState<GovernanceLookupRow[]>([]); const [detail, setDetail] = useState<UserGovernanceDetail | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const [analytics, setAnalytics] = useState<Record<string, number>>({}); const [conversations, setConversations] = useState<Array<Record<string, unknown>>>([]);
  useEffect(() => { Promise.all([adminApi.getMessagingAnalytics(), adminApi.getMessagingGovernance()]).then(([metrics, governance]) => { setAnalytics(metrics.analytics || {}); setConversations(governance.conversations || []); }).catch(() => undefined); }, []);
  async function lookup(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { setRows(await adminApi.lookupGovernanceUsers(query, type)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Lookup failed."); } finally { setBusy(false); } }
  async function select(id: string) { setBusy(true); try { setDetail(await adminApi.getUserGovernance(id)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Detail failed."); } finally { setBusy(false); } }
  async function mutate(action: string) { if (!detail) return; const reason = window.prompt(`Reason for ${action.replaceAll("_", " ").toLowerCase()}?`); if (!reason) return; if (!window.confirm(`Confirm ${action.replaceAll("_", " ").toLowerCase()} for ${detail.privateEmail}?`)) return; setBusy(true); try { await adminApi.applyUserGovernanceAction(detail.internalId, action, reason); await select(detail.internalId); } catch (cause) { setError(cause instanceof Error ? cause.message : "Action failed."); setBusy(false); } }
  return <AdminPageShell title="Messaging & User Governance" subtitle="Protected identity lookup and least-permissive messaging controls. Every lookup and mutation is audited.">
    {error ? <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div> : null}
    <section className="mb-4 grid gap-3 md:grid-cols-4">{Object.entries(analytics).map(([key, value]) => <div key={key} className="rounded-xl border bg-background p-3"><div className="text-2xl font-semibold">{value}</div><div className="text-xs text-muted-foreground">{key}</div></div>)}</section>
    <form className="grid gap-3 rounded-2xl border bg-background p-4 md:grid-cols-[1fr_180px_auto]" onSubmit={lookup}>
      <input aria-label="User lookup query" className="rounded-lg border px-3 py-2" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Display name, PawnLoop ID, exact email or internal ID" required minLength={2}/>
      <select aria-label="Lookup type" className="rounded-lg border px-3 py-2" value={type} onChange={(e) => setType(e.target.value as typeof type)}><option value="PUBLIC">Public identity</option><option value="EMAIL">Exact private email</option><option value="INTERNAL_ID">Exact internal ID</option></select>
      <button className="btn btn-primary" disabled={busy}>Protected lookup</button>
    </form>
    <div className="mt-4 grid gap-4 lg:grid-cols-[minmax(320px,0.8fr)_minmax(480px,1.2fr)]">
      <section className="rounded-2xl border bg-background p-4"><h2 className="font-semibold">Results</h2>{rows.map((row) => <button key={row.internalId} className="mt-3 block w-full rounded-xl border p-3 text-left" onClick={() => void select(row.internalId)}><strong>{row.publicDisplayName}</strong><div className="text-sm">{row.pawnLoopIdentifier} · {row.accountStatus}</div><div className="text-xs text-muted-foreground">{row.privateEmail}<br/>{row.internalId}</div></button>)}</section>
      <section className="rounded-2xl border bg-background p-4"><h2 className="font-semibold">Governance detail</h2>{detail ? <div className="mt-3 space-y-3 text-sm"><div><strong>{detail.publicDisplayName}</strong> · {detail.accountStatus} · {detail.role}</div><dl className="grid grid-cols-2 gap-2"><dt>Messaging eligible</dt><dd>{detail.messagingEligibility.allowed ? "Yes" : "No"}</dd><dt>Messaging restriction</dt><dd>{detail.messagingRestricted ? "Restricted" : "None"}</dd><dt>Shop contact</dt><dd>{detail.shopInitiatedContactDisabled ? "Disabled" : "Allowed by admin"}</dd><dt>Discoverability</dt><dd>{detail.discoverabilityRestricted ? "Administratively hidden" : "No admin restriction"}</dd><dt>First-contact consent</dt><dd>{String(detail.firstContactConsent.state)}</dd><dt>Related shops</dt><dd>{detail.shops.length}</dd><dt>Memberships</dt><dd>{detail.memberships.length}</dd></dl><details><summary>Effective permission factors</summary><pre className="overflow-auto text-xs">{JSON.stringify(detail.messagingEligibility, null, 2)}</pre></details><details><summary>Blocking and reports</summary><pre className="overflow-auto text-xs">{JSON.stringify(detail.blockingAndReports, null, 2)}</pre></details><div className="flex flex-wrap gap-2">{actions.map((action) => <button key={action} className="btn btn-secondary" disabled={busy} onClick={() => void mutate(action)}>{action.replaceAll("_", " ")}</button>)}</div></div> : <p className="mt-3 text-sm text-muted-foreground">Select a protected lookup result.</p>}</section>
    </div>
    <section className="mt-4 rounded-2xl border bg-background p-4"><h2 className="font-semibold">Conversation governance</h2><p className="text-sm text-muted-foreground">Metadata only; message bodies require the separate reasoned moderation-content route.</p><div className="mt-3 overflow-x-auto"><table className="w-full text-sm"><thead><tr><th className="text-left">Conversation</th><th>Status</th><th>Moderation</th><th>Messages</th><th>Reports</th><th>Context</th></tr></thead><tbody>{conversations.map((row) => <tr key={String(row.id)} className="border-t"><td>{String(row.id)}</td><td className="text-center">{String(row.status)}</td><td className="text-center">{String(row.moderationState)}</td><td className="text-center">{String(row.messageCount)}</td><td className="text-center">{String(row.reportCount)}</td><td className="text-center">{String(row.contextType || "—")}</td></tr>)}</tbody></table></div></section>
  </AdminPageShell>;
}
