import { useEffect, useState, type FormEvent } from "react";
import { trainingApi, type TrainingInput, type TrainingItem, type TrainingStatus } from "../../services/training";
const roles = ["CONSUMER", "OWNER", "ADMIN", "SUPER_ADMIN"] as const;
const blank: TrainingInput = { slug: "", title: "", summary: "", category: "", type: "TUTORIAL", difficulty: "BEGINNER", durationSeconds: null, videoUrl: null, featured: false, required: false, sortOrder: 0, audiences: ["CONSUMER"], steps: [{ position: 1, title: "", body: "" }] };

export default function SuperAdminTrainingPage() {
  const [items, setItems] = useState<TrainingItem[]>([]); const [editing, setEditing] = useState<TrainingItem | null>(null); const [preview, setPreview] = useState<TrainingItem | null>(null); const [status, setStatus] = useState(""); const [category, setCategory] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function load() { setLoading(true); setError(""); try { setItems((await trainingApi.adminList({ status, category })).items); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load managed training."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [status, category]); // eslint-disable-line react-hooks/exhaustive-deps
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); const form = new FormData(event.currentTarget); const type = String(form.get("type")) as TrainingInput["type"]; const input: TrainingInput = { slug: String(form.get("slug")), title: String(form.get("title")), summary: String(form.get("summary")), category: String(form.get("category")), type, difficulty: String(form.get("difficulty")) as TrainingInput["difficulty"], durationSeconds: Number(form.get("durationSeconds")) || null, videoUrl: type === "VIDEO" ? String(form.get("videoUrl")) : null, featured: form.get("featured") === "on", required: form.get("required") === "on", sortOrder: Number(form.get("sortOrder")) || 0, audiences: roles.filter((role) => form.get(`role-${role}`) === "on"), steps: type === "TUTORIAL" ? String(form.get("steps") || "").split("\n").filter(Boolean).map((line, index) => { const [title, ...body] = line.split("|"); return { position: index + 1, title: title.trim(), body: body.join("|").trim() }; }) : [] };
    try { if (editing) await trainingApi.update(editing.id, input); else await trainingApi.create(input); setEditing(null); event.currentTarget.reset(); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to save training content."); } finally { setSaving(false); } }
  async function lifecycle(item: TrainingItem, next: Exclude<TrainingStatus, "DRAFT">) { setError(""); try { await trainingApi.lifecycle(item.id, next); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to change publishing state."); } }
  async function move(item: TrainingItem, delta: number) { try { await trainingApi.reorder([{ id: item.id, sortOrder: Math.max(0, item.sortOrder + delta) }]); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to reorder content."); } }
  const initial = editing || blank;
  return <main className="training-shell"><header><p className="training-kicker">Super Admin</p><h1>Training content management</h1><p>Create, preview, target, order, publish, unpublish, and archive Knowledge Center content.</p></header>{error && <p role="alert" className="training-error">{error}</p>}
    <section><h2>{editing ? `Edit ${editing.title}` : "Create content"}</h2><form key={editing?.id || "new"} className="training-admin-form" onSubmit={submit}>
      <label>Title<input name="title" required defaultValue={initial.title} /></label><label>Slug<input name="slug" required defaultValue={initial.slug} /></label><label>Summary<textarea name="summary" required defaultValue={initial.summary} /></label><label>Category<input name="category" required defaultValue={initial.category} /></label>
      <label>Format<select name="type" defaultValue={initial.type}><option>VIDEO</option><option>TUTORIAL</option></select></label><label>Difficulty<select name="difficulty" defaultValue={initial.difficulty}><option>BEGINNER</option><option>INTERMEDIATE</option><option>ADVANCED</option></select></label><label>Duration seconds<input name="durationSeconds" type="number" min="0" defaultValue={initial.durationSeconds || ""} /></label><label>Sort order<input name="sortOrder" type="number" min="0" defaultValue={initial.sortOrder} /></label><label className="training-wide">Approved video URL<input name="videoUrl" type="url" defaultValue={initial.videoUrl || ""} placeholder="https://www.youtube.com/watch?v=…" /></label><label className="training-wide">Tutorial steps (one per line: title | instructions)<textarea name="steps" defaultValue={initial.steps.map((step) => `${step.title} | ${step.body}`).join("\n")} /></label>
      <fieldset><legend>Audiences</legend>{roles.map((role) => <label key={role}><input type="checkbox" name={`role-${role}`} defaultChecked={initial.audiences.includes(role)} /> {role}</label>)}</fieldset><label><input type="checkbox" name="featured" defaultChecked={initial.featured} /> Featured</label><label><input type="checkbox" name="required" defaultChecked={initial.required} /> Required</label><div className="training-actions"><button disabled={saving}>{saving ? "Saving…" : editing ? "Save changes" : "Create draft"}</button>{editing && <button type="button" onClick={() => setEditing(null)}>Cancel</button>}</div>
    </form></section>
    <section><div className="training-filters"><select aria-label="Filter status" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All states</option><option>DRAFT</option><option>PUBLISHED</option><option>UNPUBLISHED</option><option>ARCHIVED</option></select><input aria-label="Filter category" placeholder="Category" value={category} onChange={(e) => setCategory(e.target.value)} /></div><h2>Content library</h2>{loading ? <p role="status">Loading managed content…</p> : !items.length ? <div className="training-empty">No content matches these filters.</div> : <div className="training-admin-list">{items.map((item) => <article key={item.id}><h3>{item.title}</h3><p>{item.status} · {item.category} · order {item.sortOrder}</p><p>{item.statistics?.started || 0} started · {item.statistics?.completed || 0} completed</p><div className="training-actions"><button onClick={() => setPreview(item)}>Preview</button>{item.status !== "ARCHIVED" && <button onClick={() => setEditing(item)}>Edit</button>}<button onClick={() => void move(item, -1)}>↑</button><button onClick={() => void move(item, 1)}>↓</button>{item.status !== "PUBLISHED" && item.status !== "ARCHIVED" && <button onClick={() => void lifecycle(item, "PUBLISHED")}>Publish</button>}{item.status === "PUBLISHED" && <button onClick={() => void lifecycle(item, "UNPUBLISHED")}>Unpublish</button>}{item.status !== "ARCHIVED" && <button onClick={() => void lifecycle(item, "ARCHIVED")}>Archive</button>}</div></article>)}</div>}</section>
    {preview && <section className="training-preview"><button onClick={() => setPreview(null)}>Close preview</button><h2>{preview.title}</h2><p>{preview.summary}</p>{preview.videoUrl && <p>{preview.videoUrl}</p>}{preview.steps.map((step) => <div key={step.position}><h3>{step.position}. {step.title}</h3><p>{step.body}</p></div>)}</section>}
  </main>;
}
