import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { ConfirmationDialog, DetailDrawer, EmptyState, ErrorState, FilterPanel, LoadingState, MetricCard, OperationsHeader, StatusBadge, Toolbar, type ConfirmationSpec } from "../components/SuperAdminOperations";
import { adminApi, type GovernanceLookupRow, type UserGovernanceDetail } from "../services/adminApi";

const ACTIONS = ["SUSPEND_ACCOUNT", "RESTORE_ACCOUNT", "RESTRICT_MESSAGING", "RESTORE_MESSAGING", "DISABLE_SHOP_CONTACT", "RESTORE_SHOP_CONTACT", "RESTRICT_DISCOVERABILITY", "RESTORE_DISCOVERABILITY"];
const TABS = ["Users", "Conversations", "Abuse Reports", "Policy", "Activity / Audit"] as const;
type Tab = typeof TABS[number];

export default function SuperAdminGovernancePage() {
  const [tab, setTab] = useState<Tab>("Users"); const [query, setQuery] = useState(""); const [type, setType] = useState<"PUBLIC" | "EMAIL" | "INTERNAL_ID">("PUBLIC");
  const [rows, setRows] = useState<GovernanceLookupRow[]>([]); const [detail, setDetail] = useState<UserGovernanceDetail | null>(null); const [analytics, setAnalytics] = useState<Record<string, number>>({}); const [conversations, setConversations] = useState<Array<Record<string, unknown>>>([]);
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [updatedAt, setUpdatedAt] = useState<Date | null>(null); const [pending, setPending] = useState<{ action: string; spec: ConfirmationSpec } | null>(null); const [reason, setReason] = useState(""); const [confirmation, setConfirmation] = useState("");
  const refresh = useCallback(async () => { setBusy(true); setError(""); try { const [metrics, governance] = await Promise.all([adminApi.getMessagingAnalytics(), adminApi.getMessagingGovernance()]); setAnalytics(metrics.analytics || {}); setConversations(governance.conversations || []); setUpdatedAt(new Date()); } catch (cause) { setError(cause instanceof Error ? cause.message : "Governance data is unavailable."); } finally { setBusy(false); } }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  async function lookup(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { setRows(await adminApi.lookupGovernanceUsers(query.trim(), type)); setUpdatedAt(new Date()); } catch (cause) { setError(cause instanceof Error ? cause.message : "Lookup failed."); } finally { setBusy(false); } }
  async function select(id: string) { setBusy(true); setError(""); try { setDetail(await adminApi.getUserGovernance(id)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Detail failed."); } finally { setBusy(false); } }
  function requestAction(action: string) { if (!detail) return; const label = action.replaceAll("_", " ").toLowerCase(); setReason(""); setConfirmation(""); setPending({ action, spec: { action: label, target: `${detail.publicDisplayName} (${detail.pawnLoopIdentifier})`, impact: "Changes effective account permissions. User consent and user-controlled blocks remain unchanged.", highRisk: ["SUSPEND_ACCOUNT", "RESTRICT_MESSAGING", "DISABLE_SHOP_CONTACT", "RESTRICT_DISCOVERABILITY"].includes(action), confirmText: action } }); }
  async function confirmAction() { if (!detail || !pending) return; setBusy(true); setError(""); try { await adminApi.applyUserGovernanceAction(detail.internalId, pending.action, reason.trim()); setPending(null); await select(detail.internalId); } catch (cause) { setError(cause instanceof Error ? cause.message : "Action failed."); setBusy(false); } }
  return <div>
    <OperationsHeader title="Governance Control Center" description="Protected identity, messaging safety, policy, and audited administrative restrictions." updatedAt={updatedAt} actions={<button className="btn btn-secondary" onClick={() => void refresh()} disabled={busy}>Refresh</button>} />
    <Toolbar label="Governance sections">{TABS.map((item) => <button key={item} className={tab === item ? "btn btn-primary" : "btn btn-secondary"} aria-pressed={tab === item} onClick={() => setTab(item)}>{item}</button>)}</Toolbar>
    {error ? <ErrorState message={error} onRetry={() => void refresh()} /> : null}
    <div className="ops-metrics">{Object.entries(analytics).slice(0, 8).map(([key, value]) => <MetricCard key={key} label={key.replaceAll(/([A-Z])/g, " $1").replaceAll("_", " ")} value={value} />)}</div>
    {tab === "Users" ? <>
      <FilterPanel title="Protected identity lookup"><form className="ops-filter__grid" onSubmit={lookup}><label>Identity<input aria-label="User lookup query" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Display name, PawnLoop ID, email, or internal ID" required minLength={2} /></label><label>Lookup scope<select aria-label="Lookup type" value={type} onChange={(event) => setType(event.target.value as typeof type)}><option value="PUBLIC">Public identity</option><option value="EMAIL">Exact private email</option><option value="INTERNAL_ID">Exact internal ID</option></select></label><button className="btn btn-primary" disabled={busy}>Run audited lookup</button></form></FilterPanel>
      {busy && !rows.length ? <LoadingState label="Loading governance users…" /> : rows.length ? <section className="ops-panel"><h2>Results</h2>{rows.map((row) => <button key={row.internalId} className="list-card" onClick={() => void select(row.internalId)}><strong>{row.publicDisplayName}</strong><span>{row.pawnLoopIdentifier}</span> <StatusBadge value={row.accountStatus} /></button>)}</section> : <EmptyState title="No protected results" description="Run a narrowly scoped lookup. Private identifiers are shown only after an audited lookup." />}
    </> : null}
    {tab === "Conversations" ? <section className="ops-panel"><h2>Conversation metadata</h2><p className="muted">Message bodies are excluded. Protected content requires a separate reasoned and audited access request.</p>{conversations.length ? <div className="table-wrap"><table><thead><tr><th>Conversation</th><th>Status</th><th>Moderation</th><th>Messages</th><th>Reports</th></tr></thead><tbody>{conversations.map((row) => <tr key={String(row.id)}><td>{String(row.id)}</td><td><StatusBadge value={String(row.status)} /></td><td>{String(row.moderationState)}</td><td>{String(row.messageCount)}</td><td>{String(row.reportCount)}</td></tr>)}</tbody></table></div> : <EmptyState title="No conversations" description="No conversation metadata matches the current governance scope." />}</section> : null}
    {tab === "Abuse Reports" ? <EmptyState title="Abuse reports remain metadata-only" description="Reports are summarized in governance analytics. Open conversation governance to inspect authorized context without exposing message bodies." /> : null}
    {tab === "Policy" ? <section className="ops-panel"><h2>Effective policy</h2><p>Administrative controls can narrow access, never override consent or user-controlled blocking. Account suspension invalidates active sessions. Protected content access requires a documented reason and separate durable audit event.</p></section> : null}
    {tab === "Activity / Audit" ? <EmptyState title="Governance activity is immutable" description="Use the audit workspace to filter by actor, action, target, request ID, and result." action={<Link className="btn btn-primary" to="/super-admin/audit">Open audit logs</Link>} /> : null}
    <DetailDrawer open={Boolean(detail)} title={detail ? `Governance · ${detail.publicDisplayName}` : "Governance detail"} onClose={() => setDetail(null)}>{detail ? <div className="page-stack"><p>{detail.pawnLoopIdentifier} · <StatusBadge value={detail.accountStatus} /></p><dl><dt>Messaging</dt><dd>{detail.messagingEligibility.allowed ? "Allowed" : "Restricted"}</dd><dt>Shop contact</dt><dd>{detail.shopInitiatedContactDisabled ? "Administratively disabled" : "Subject to consent"}</dd><dt>Discoverability</dt><dd>{detail.discoverabilityRestricted ? "Administratively hidden" : "Subject to user settings"}</dd><dt>Effective policy</dt><dd>{detail.messagingEligibility.policy}</dd></dl><details><summary>Permission factors</summary><pre>{JSON.stringify(detail.messagingEligibility.factors, null, 2)}</pre></details><Toolbar label="Governance actions">{ACTIONS.map((action) => <button className="btn btn-secondary" key={action} disabled={busy} onClick={() => requestAction(action)}>{action.replaceAll("_", " ")}</button>)}</Toolbar></div> : null}</DetailDrawer>
    <ConfirmationDialog spec={pending?.spec || null} reason={reason} confirmation={confirmation} busy={busy} onReasonChange={setReason} onConfirmationChange={setConfirmation} onCancel={() => setPending(null)} onConfirm={() => void confirmAction()} />
  </div>;
}
