import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import test from "node:test";
import { verifyProductionReleaseEvidence } from "../verify-production-release.mjs";

const releaseSha = "0123456789abcdef0123456789abcdef01234567"; const blobSha = "abcdef0123456789abcdef0123456789abcdef01"; const now = Date.parse("2026-08-15T20:00:00Z"); const time = "2026-08-15T19:50:00Z";
const manifest = Buffer.from(JSON.stringify({ recordType: "git-blob", repository: "alex3217/pawnshop-app", releaseSha })); const manifestSha256 = createHash("sha256").update(manifest).digest("hex");
const input = () => ({ repository: "alex3217/pawnshop-app", expectedSha: releaseSha, github: { generalRun: { id: "10001", url: "https://github.com/alex3217/pawnshop-app/actions/runs/10001", attempt: 1 }, databaseRun: { id: "10002", url: "https://github.com/alex3217/pawnshop-app/actions/runs/10002", attempt: 2, jobId: "90001" } }, cloudflare: { accountId: "0230f5ea7416d81f9f931bb02545abdb", project: "pawnloop-frontend", deploymentId: "2e3d541f-4cb8-4469-bce0-296b64ed8318", url: "https://2e3d541f-4cb8-4469-bce0-296b64ed8318.pawnloop-frontend.pages.dev/" }, render: { serviceId: "srv-production123", environmentId: "evm-production123", deploymentId: "dep-production123", origin: "https://pawnshop-app-bu8g.onrender.com/", url: "https://dashboard.render.com/web/srv-production123/deploys/dep-production123" }, releaseRecord: { type: "git-blob", blobSha, manifestSha256, path: "docs/releases/release.json", url: `https://github.com/alex3217/pawnshop-app/blob/${releaseSha}/docs/releases/release.json` } });
const clients = () => ({
  github: { getCommit: async () => ({ repository: "alex3217/pawnshop-app", sha: releaseSha }), getWorkflowRun: async ({ runId }) => runId === "10001" ? { repository: "alex3217/pawnshop-app", id: 10001, name: "PawnShop Core CI", path: ".github/workflows/core-ci.yml", event: "push", conclusion: "success", status: "completed", headSha: releaseSha, runAttempt: 1, url: "https://github.com/alex3217/pawnshop-app/actions/runs/10001", createdAt: time, completedAt: time } : { repository: "alex3217/pawnshop-app", id: 10002, name: "PawnLoop Production Database Migration", path: ".github/workflows/production-database.yml", event: "workflow_dispatch", conclusion: "success", status: "completed", headSha: releaseSha, runAttempt: 2, url: "https://github.com/alex3217/pawnshop-app/actions/runs/10002", createdAt: time, completedAt: time, jobs: [{ id: 90001, conclusion: "success", steps: [{ name: "Apply certified production migrations", conclusion: "success" }, { name: "Reconcile migration outcome and emit sanitized evidence", conclusion: "success" }] }] }, getGitBlob: async () => ({ repository: "alex3217/pawnshop-app", sha: blobSha, encoding: "base64", content: manifest.toString("base64") }) },
  cloudflare: { getDeployment: async () => ({ accountId: "0230f5ea7416d81f9f931bb02545abdb", project: "pawnloop-frontend", id: "2e3d541f-4cb8-4469-bce0-296b64ed8318", environment: "production", status: "success", branch: "main", sourceSha: releaseSha, url: "https://2e3d541f-4cb8-4469-bce0-296b64ed8318.pawnloop-frontend.pages.dev/", createdAt: time }) },
  render: { getService: async () => ({ id: "srv-production123", name: "pawnshop-app", environmentId: "evm-production123", environmentName: "Production", origin: "https://pawnshop-app-bu8g.onrender.com/" }), getDeployment: async () => ({ id: "dep-production123", serviceId: "srv-production123", environmentId: "evm-production123", status: "live", sourceSha: releaseSha, verifiedAt: time }) },
});
async function guard(mutate, pattern) { const value = input(); const providers = clients(); mutate(value, providers); await assert.rejects(verifyProductionReleaseEvidence(value, { clients: providers, now }), (error) => { assert.equal(error.code, "PRODUCTION_RELEASE_VERIFICATION_FAILED"); assert.match(error.guard, pattern); return true; }); }

test("independently retrieves and binds every provider record and immutable manifest", async () => { assert.equal((await verifyProductionReleaseEvidence(input(), { clients: clients(), now })).verified, true); });
test("operator JSON without provider clients and fabricated provider records cannot pass", async () => { await guard((v, p) => { p.github.getCommit = async () => ({ repository: v.repository, sha: `f${releaseSha.slice(1)}` }); }, /commit identity/); await assert.rejects(verifyProductionReleaseEvidence(input(), { now }), /provider client/); });
test("rejects GitHub URL/run-ID, repository, workflow, attempt, SHA, and reused-run mismatches", async () => {
  await guard((v) => { v.github.generalRun.url = "https://github.com/alex3217/pawnshop-app/actions/runs/99999"; }, /URL identity/); await guard((v, p) => { p.github.getWorkflowRun = async () => ({ repository: "attacker/repo" }); }, /wrong repository/); await guard((v, p) => { const old = p.github.getWorkflowRun; p.github.getWorkflowRun = async (x) => ({ ...(await old(x)), name: "Other" }); }, /workflow identity/); await guard((v) => { v.github.generalRun.attempt = 9; }, /attempt/); await guard((v) => { v.github.databaseRun.id = "10001"; v.github.databaseRun.url = v.github.generalRun.url; }, /reused/);
});
test("rejects Cloudflare deployment URL/ID, account, project, environment, and source mismatches", async () => {
  await guard((v) => { v.cloudflare.url = "https://aaaaaaaa-4cb8-4469-bce0-296b64ed8318.pawnloop-frontend.pages.dev/"; }, /URL identity/); await guard((v, p) => { p.cloudflare.getDeployment = async () => ({ accountId: "wrong" }); }, /account/); await guard((v) => { v.cloudflare.project = "other"; }, /project/); await guard((v, p) => { const old = p.cloudflare.getDeployment; p.cloudflare.getDeployment = async (x) => ({ ...(await old(x)), environment: "preview" }); }, /environment/);
});
test("rejects Render deployment URL/ID, service, environment, origin, status, and source mismatches", async () => {
  await guard((v) => { v.render.url = "https://dashboard.render.com/web/srv-production123/deploys/dep-other123"; }, /URL identity/); await guard((v, p) => { p.render.getDeployment = async () => ({ id: "dep-other123" }); }, /deployment identity/); await guard((v, p) => { const old = p.render.getService; p.render.getService = async (x) => ({ ...(await old(x)), environmentName: "Staging" }); }, /environment/); await guard((v) => { v.render.origin = "https://pawnshop-app-bu8g.onrender.com.evil.test/"; }, /origin identity/);
});
test("rejects mutable GitHub issues and invalid or missing Git blob digest", async () => {
  await guard((v) => { v.releaseRecord = { type: "github-issue", url: "https://github.com/alex3217/pawnshop-app/issues/314" }; }, /mutable release records/); await guard((v) => { v.releaseRecord.manifestSha256 = "0".repeat(64); }, /digest mismatch/); await guard((v) => { delete v.releaseRecord.manifestSha256; }, /SHA-256.*malformed/);
});
test("rejects stale, future, and reused timestamps by the timestamp guard", async () => {
  await guard((v, p) => { const old = p.cloudflare.getDeployment; p.cloudflare.getDeployment = async (x) => ({ ...(await old(x)), createdAt: "2026-08-01T00:00:00Z" }); }, /stale or reused/); await guard((v, p) => { const old = p.render.getDeployment; p.render.getDeployment = async (x) => ({ ...(await old(x)), verifiedAt: "2026-08-16T01:00:00Z" }); }, /future-dated/);
});
