import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { getBuyerPlanUsage, type BuyerPlanUsage } from "../services/buyerPlans";
import { getMySavedSearches, type SavedSearch } from "../services/savedSearches";
import { getMyWatchlist, type WatchlistEntry } from "../services/watchlist";
import { getFollowedShops, type FollowedShop } from "../services/customerEngagement";

export default function BuyerWorkspacePage() {
  const [usage, setUsage] = useState<BuyerPlanUsage | null>(null); const [searches, setSearches] = useState<SavedSearch[]>([]); const [watchlist, setWatchlist] = useState<WatchlistEntry[]>([]); const [followedShops, setFollowedShops] = useState<FollowedShop[]>([]); const [error, setError] = useState("");
  useEffect(() => { Promise.all([getBuyerPlanUsage(), getMySavedSearches(), getMyWatchlist(), getFollowedShops()]).then(([nextUsage, nextSearches, nextWatchlist, nextFollows]) => { setUsage(nextUsage); setSearches(nextSearches); setWatchlist(nextWatchlist); setFollowedShops(nextFollows.followedShops); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Unable to load My Activity.")); }, []);
  return <main style={{ maxWidth: 1120, margin: "0 auto", padding: "28px 20px 60px" }}><header><p className="section-eyebrow">BUYER TOOLS</p><h1>My Activity</h1><p>A focused view of the buyer tools already active on your account.</p></header>{error ? <div role="alert" className="error-text">{error}</div> : null}{!usage && !error ? <p aria-live="polite">Loading activity…</p> : null}
    {usage ? <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: 14, marginTop: 18 }}><section className="list-card"><h2>Followed shops</h2>{followedShops.length === 0 ? <p>No followed shops yet. Following is always an explicit action from a shop storefront.</p> : <ul>{followedShops.map(({ shop, follow }) => <li key={shop.id}><Link to={`/shops/${shop.slug || shop.id}`}>{shop.name}</Link> · {follow.paused ? "alerts paused" : "alerts managed"}</li>)}</ul>}<Link to="/shops">Browse shops</Link></section><section className="list-card"><h2>Watchlist</h2><p>{watchlist.length} saved item{watchlist.length === 1 ? "" : "s"}. This is your Phase 1 default wish list.</p><Link to="/watchlist">Open watchlist</Link></section><section className="list-card"><h2>Saved searches</h2><p>{searches.length} of {usage.usage.savedSearches.unlimited ? "unlimited" : usage.usage.savedSearches.limit} used.</p><Link to="/saved-searches">Manage saved searches</Link></section><section className="list-card"><h2>Purchases and offers</h2><p>Core commerce is available on every buyer plan.</p><Link to="/marketplace/purchases">Track purchases</Link> · <Link to="/offers">Open offers</Link></section><section className="list-card"><h2>Auctions</h2><p>Track active bids and completed wins without a paid-plan gate.</p><Link to="/my-bids">My bids</Link> · <Link to="/my-wins">My wins</Link></section><section className="list-card"><h2>Workspace plan</h2><p>{usage.subscription.displayName} · {usage.entitlements.workspaceLevel} layout</p>{usage.entitlements.workspaceCustomizationEnabled ? <p>Customization eligibility is represented; configurable widgets are deferred.</p> : <Link to="/buyer/subscription">See workspace upgrades</Link>}</section><section className="list-card"><h2>Sell or pawn</h2><p>Reuse the existing item submission and shop-offer workflow.</p><Link to="/buyer/sell-item">Start or track a request</Link></section></div> : null}
  </main>;
}
