import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { getBuyerMessagingProfile, unblockBuyerMessagingShop, updateBuyerMessagingProfile, type BuyerMessagingProfile } from "../services/buyerMessagingProfile";
import "../styles/shop-messaging.css";

export default function BuyerMessagingProfilePage() {
  const [profile, setProfile] = useState<BuyerMessagingProfile | null>(null); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  useEffect(() => { const controller = new AbortController(); void getBuyerMessagingProfile(controller.signal).then((result) => setProfile(result.profile)).catch((error) => setNotice(error instanceof Error ? error.message : "Could not load messaging settings.")); return () => controller.abort(); }, []);
  async function save(event: React.FormEvent) { event.preventDefault(); if (!profile) return; setBusy(true); setNotice(""); try { const result = await updateBuyerMessagingProfile({ publicDisplayName: profile.publicDisplayName, publicMessageIdentifier: profile.publicMessageIdentifier, messageDiscoverable: profile.messageDiscoverable, allowShopFirstContact: profile.allowShopFirstContact, allowTransactionalMessages: profile.allowTransactionalMessages }); setProfile(result.profile); setNotice("Messaging profile saved."); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not save messaging settings."); } finally { setBusy(false); } }
  if (!profile) return <main className="messaging-page"><p role="status">{notice || "Loading messaging profile…"}</p></main>;
  return <main className="messaging-page"><section className="messaging-panel"><div className="messages-title"><div><h1>Profile &amp; messaging settings</h1><p>Control the public identity pawnshops can use to find you.</p></div><Link to="/messages">Back to messages</Link></div><form className="messaging-form" onSubmit={save}><label>Public display name<input required minLength={2} maxLength={60} value={profile.publicDisplayName || ""} onChange={(event) => setProfile({ ...profile, publicDisplayName: event.target.value })} /><small>Shown to pawnshops instead of your legal or account name.</small></label><label>PawnLoop public identifier<div className="identifier-input"><span>@</span><input required minLength={3} maxLength={32} pattern="[a-z0-9][a-z0-9_-]{2,31}" value={profile.publicMessageIdentifier} onChange={(event) => setProfile({ ...profile, publicMessageIdentifier: event.target.value.toLowerCase() })} /></div></label><div className="private-account-email"><strong>Private account email</strong><span>{profile.email}</span><small>Never public and never searchable by pawnshops.</small></div><fieldset><legend>Privacy and consent</legend><label><input type="checkbox" checked={profile.messageDiscoverable} onChange={(event) => setProfile({ ...profile, messageDiscoverable: event.target.checked, ...(!event.target.checked ? { allowShopFirstContact: false } : {}) })} /> Allow pawnshops to find me</label><label><input type="checkbox" disabled={!profile.messageDiscoverable} checked={profile.allowShopFirstContact} onChange={(event) => setProfile({ ...profile, allowShopFirstContact: event.target.checked })} /> Allow pawnshops to message me first</label><label><input type="checkbox" checked={profile.allowTransactionalMessages} onChange={(event) => setProfile({ ...profile, allowTransactionalMessages: event.target.checked })} /> Allow transactional messages</label></fieldset><button disabled={busy}>{busy ? "Saving…" : "Save settings"}</button></form><section className="blocked-shops"><h2>Blocked pawnshops</h2>{profile.blockedMessagingShops.length ? profile.blockedMessagingShops.map(({ shop }) => <div key={shop.id}><div><strong>{shop.name}</strong><span>{[shop.city, shop.state].filter(Boolean).join(", ")}</span></div><button type="button" className="secondary" onClick={async () => { await unblockBuyerMessagingShop(shop.id); setProfile({ ...profile, blockedMessagingShops: profile.blockedMessagingShops.filter((row) => row.shop.id !== shop.id) }); }}>Unblock</button></div>) : <p>No blocked pawnshops.</p>}</section>{notice ? <p role="status">{notice}</p> : null}</section></main>;
}
