import { useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { changeParticipantConversationState, changeShopConversationStatus, getShopConversation, markShopConversationRead, reportShopConversation, sendShopMessage, type ShopConversation } from "../services/shopMessaging";
import "../styles/shop-messaging.css";

export default function ConversationPage() {
  const { id = "" } = useParams(); const [row, setRow] = useState<ShopConversation | null>(null); const [side, setSide] = useState<"SELLER" | "SHOP" | "RECIPIENT">("SELLER"); const [viewerShopId, setViewerShopId] = useState<string | null>(null); const [message, setMessage] = useState(""); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { try { const result = await getShopConversation(id); setRow(result.conversation); setSide(result.side); setViewerShopId(result.viewerShopId || null); await markShopConversationRead(id); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load conversation."); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  async function send(event: React.FormEvent) { event.preventDefault(); try { await sendShopMessage(id, message); setMessage(""); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not send message."); } }
  async function status(action: "close" | "reopen" | "block") { try { await changeShopConversationStatus(id, action); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not update conversation."); } }
  async function participantAction(action: "mute" | "unmute" | "archive" | "unarchive") { try { await changeParticipantConversationState(id, action); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not update conversation."); } }
  if (loading) return <main className="messaging-page"><p role="status">Loading conversation…</p></main>; if (!row) return <main className="messaging-page"><p role="alert">{error || "Conversation not found."}</p></main>;
  const personConversation = Boolean(row.recipientUser); const muted = side === "RECIPIENT" ? row.recipientMutedAt : row.sellerMutedAt; const archived = side === "RECIPIENT" ? row.recipientArchivedAt : row.sellerArchivedAt; const otherName = side === "RECIPIENT" ? row.seller.publicDisplayName || row.seller.name : row.recipientUser?.publicDisplayName || row.shop?.name || "PawnLoop member";
  return <main className="messaging-page"><section className="messaging-panel"><Link to={side === "SHOP" ? "/owner/messages" : "/messages"}>← Back to messages</Link><header className="conversation-header"><div><h1>{row.subject}</h1><p>{side === "SHOP" ? row.recipientShop?.name || row.seller.name : otherName} · {row.contactReason.replaceAll("_", " ")}</p>{row.shop ? <Link to={`/shops/${row.shop.id}`}>View shop</Link> : null}</div><span className={`message-status status-${row.status.toLowerCase()}`}>{row.status}</span></header><div className="message-thread" aria-live="polite">{row.messages.map((item) => { const mine = side === "SHOP" ? item.systemMetadata?.sentByShopId === viewerShopId : side === "RECIPIENT" ? item.senderUserId === row.recipientUser?.id : item.senderUserId === row.sellerUserId; return <article key={item.id} className={mine ? "message-bubble shop" : "message-bubble seller"}><strong>{mine ? "You" : otherName}</strong><p>{item.body}</p><time>{new Date(item.createdAt).toLocaleString()}</time></article>; })}</div>{error ? <p role="alert" className="messaging-error">{error}</p> : null}{row.status === "OPEN" ? <form onSubmit={send} className="messaging-form"><label>Reply<textarea required maxLength={4000} rows={4} value={message} onChange={(e) => setMessage(e.target.value)} /></label><button>Send reply</button></form> : <p className="messaging-empty">This conversation is {row.status.toLowerCase()}. Reopen it to continue.</p>}<div className="messaging-actions">{row.status === "OPEN" ? <button onClick={() => status("close")}>Close</button> : row.status === "CLOSED" ? <button onClick={() => status("reopen")}>Reopen</button> : null}{personConversation ? <><button onClick={() => participantAction(muted ? "unmute" : "mute")}>{muted ? "Unmute" : "Mute"}</button><button onClick={() => participantAction(archived ? "unarchive" : "archive")}>{archived ? "Unarchive" : "Archive"}</button></> : null}<button onClick={() => { const reason = window.prompt("Briefly describe the issue"); if (reason) void reportShopConversation(id, reason); }}>Report</button>{row.status !== "BLOCKED" ? <button className="danger" onClick={() => status("block")}>Block</button> : null}</div></section></main>;
}
