import { useCallback, useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { changeShopConversationStatus, getShopConversation, markShopConversationRead, reportShopConversation, sendShopMessage, type ShopConversation } from "../services/shopMessaging";
import "../styles/shop-messaging.css";

export default function ConversationPage() {
  const { id = "" } = useParams(); const [row, setRow] = useState<ShopConversation | null>(null); const [side, setSide] = useState<"SELLER" | "SHOP">("SELLER"); const [message, setMessage] = useState(""); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { try { const result = await getShopConversation(id); setRow(result.conversation); setSide(result.side); await markShopConversationRead(id); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load conversation."); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  async function send(event: React.FormEvent) { event.preventDefault(); try { await sendShopMessage(id, message); setMessage(""); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not send message."); } }
  async function status(action: "close" | "reopen" | "block") { try { await changeShopConversationStatus(id, action); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not update conversation."); } }
  if (loading) return <main className="messaging-page"><p role="status">Loading conversation…</p></main>; if (!row) return <main className="messaging-page"><p role="alert">{error || "Conversation not found."}</p></main>;
  return <main className="messaging-page"><section className="messaging-panel"><Link to={side === "SHOP" ? "/owner/messages" : "/messages"}>← Back to messages</Link><header className="conversation-header"><div><h1>{row.subject}</h1><p>{side === "SHOP" ? row.seller.name : row.shop.name} · {row.contactReason.replaceAll("_", " ")}</p><Link to={`/shops/${row.shop.id}`}>View shop</Link></div><span className={`message-status status-${row.status.toLowerCase()}`}>{row.status}</span></header><div className="message-thread" aria-live="polite">{row.messages.map((item) => <article key={item.id} className={item.senderUserId === row.sellerUserId ? "message-bubble seller" : "message-bubble shop"}><strong>{item.senderUserId === row.sellerUserId ? row.seller.name : row.shop.name}</strong><p>{item.body}</p><time>{new Date(item.createdAt).toLocaleString()}</time></article>)}</div>{error ? <p role="alert" className="messaging-error">{error}</p> : null}{row.status === "OPEN" ? <form onSubmit={send} className="messaging-form"><label>Reply<textarea required maxLength={4000} rows={4} value={message} onChange={(e) => setMessage(e.target.value)} /></label><button>Send reply</button></form> : <p className="messaging-empty">This conversation is {row.status.toLowerCase()}. Reopen it to continue.</p>}<div className="messaging-actions">{row.status === "OPEN" ? <button onClick={() => status("close")}>Close</button> : row.status === "CLOSED" ? <button onClick={() => status("reopen")}>Reopen</button> : null}<button onClick={() => { const reason = window.prompt("Briefly describe the issue"); if (reason) void reportShopConversation(id, reason); }}>Report</button>{side === "SHOP" && row.status !== "BLOCKED" ? <button className="danger" onClick={() => status("block")}>Block</button> : null}</div></section></main>;
}
