import { useEffect, useMemo, useRef, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { getMyShopAccess, shopHasPermission, type ShopAccessSnapshot } from "../services/shopAccess";
import { getMyShops } from "../services/shops";
import { createShopOutboundConversation, listSellerConversations, listShopConversations, searchShopMessageRecipients, type MessageRecipient, type ShopConversation } from "../services/shopMessaging";
import "../styles/shop-messaging.css";

const CONTEXTS = [
  ["GENERAL_INQUIRY", "General inquiry"], ["MARKETPLACE_LISTING", "Marketplace listing"],
  ["TARGETED_OFFER", "Targeted offer"], ["EXISTING_OFFER", "Existing offer"],
  ["ORDER_TRANSACTION", "Order or transaction"], ["AUCTION", "Auction"],
  ["SELL_PAWN_SUBMISSION", "Sell / pawn submission"],
] as const;

function ComposeDialog({ shops, access, initialShopId, onClose, onSent }: { shops: Array<{ id: string; name: string }>; access: ShopAccessSnapshot | null; initialShopId: string; onClose: () => void; onSent: (row: ShopConversation) => void }) {
  const dialogRef = useRef<HTMLDialogElement>(null); const [shopId, setShopId] = useState(initialShopId || shops[0]?.id || "");
  const [recipientType, setRecipientType] = useState<"CUSTOMER" | "PAWNSHOP">("CUSTOMER"); const [query, setQuery] = useState(""); const [results, setResults] = useState<MessageRecipient[]>([]); const [recipient, setRecipient] = useState<MessageRecipient | null>(null);
  const [subject, setSubject] = useState(""); const [contextType, setContextType] = useState("GENERAL_INQUIRY"); const [contextReferenceId, setContextReferenceId] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [sending, setSending] = useState(false); const idempotencyKey = useRef(crypto.randomUUID());
  const writableShops = useMemo(() => shops.filter((shop) => shopHasPermission(access, shop.id, "messages:write")), [access, shops]);
  useEffect(() => { dialogRef.current?.showModal(); }, []);
  useEffect(() => { setRecipient(null); setQuery(""); setResults([]); setError(""); }, [shopId, recipientType]);
  useEffect(() => { if (recipient || query.trim().length < 2 || !shopId) { setResults([]); return; } const controller = new AbortController(); const timer = window.setTimeout(() => { setError("Searching recipients…"); void searchShopMessageRecipients(shopId, recipientType, query, controller.signal).then((value) => { setResults(value.recipients); setError(value.recipients.length ? "" : "No matching recipients found."); }).catch((cause) => { if (!(cause instanceof DOMException && cause.name === "AbortError")) setError(cause instanceof Error ? cause.message : "Recipient search failed."); }); }, 250); return () => { window.clearTimeout(timer); controller.abort(); }; }, [query, recipient, recipientType, shopId]);
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); if (!recipient) return setError("Select a recipient from the search results."); if (contextType !== "GENERAL_INQUIRY" && !contextReferenceId.trim()) return setError("Enter the related platform identifier."); setSending(true); try { const result = await createShopOutboundConversation({ shopId, recipientType, recipientIdentifier: recipient.identifier, subject, contextType, contextReferenceId: contextReferenceId.trim() || undefined, message }, idempotencyKey.current); onSent(result.conversation); } catch (cause) { setError(cause instanceof Error ? cause.message : "Message could not be sent."); setSending(false); } }
  return <dialog ref={dialogRef} className="compose-dialog" aria-labelledby="compose-title" onCancel={(event) => { event.preventDefault(); onClose(); }}><form className="messaging-form" onSubmit={submit} noValidate><div className="compose-heading"><h2 id="compose-title">Compose message</h2><button type="button" className="compose-close" aria-label="Close compose message" onClick={onClose}>×</button></div>{writableShops.length > 1 ? <label>Sending shop<select value={shopId} onChange={(event) => setShopId(event.target.value)}>{writableShops.map((shop) => <option key={shop.id} value={shop.id}>{shop.name}</option>)}</select></label> : <p><strong>Sending as:</strong> {writableShops[0]?.name}</p>}<fieldset><legend>Recipient type</legend><label><input type="radio" checked={recipientType === "CUSTOMER"} onChange={() => setRecipientType("CUSTOMER")} /> Buyer / seller</label><label><input type="radio" checked={recipientType === "PAWNSHOP"} onChange={() => setRecipientType("PAWNSHOP")} /> Pawnshop</label></fieldset><label>Recipient search<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Public name or platform identifier" autoComplete="off" /></label>{results.length ? <div className="recipient-results" role="listbox" aria-label="Recipient search results">{results.map((row) => <button type="button" role="option" aria-selected={recipient?.identifier === row.identifier} key={row.identifier} onClick={() => { setRecipient(row); setQuery(row.displayName); setResults([]); }}><strong>{row.displayName}</strong>{row.detail ? <small>{row.detail}</small> : null}</button>)}</div> : null}<label>Subject or conversation topic<input value={subject} maxLength={120} required onChange={(event) => setSubject(event.target.value)} /></label><label>Context<select value={contextType} onChange={(event) => setContextType(event.target.value)}>{CONTEXTS.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label>{contextType !== "GENERAL_INQUIRY" ? <label>Related platform identifier<input value={contextReferenceId} onChange={(event) => setContextReferenceId(event.target.value)} required /></label> : null}<label>Message<textarea rows={7} value={message} maxLength={4000} required onChange={(event) => setMessage(event.target.value)} /></label><div className="compose-meta"><span>{message.length} / 4000 characters</span>{error ? <span role="alert" className="messaging-error">{error}</span> : null}</div><div className="messaging-actions"><button type="submit" disabled={sending || !recipient || !subject.trim() || !message.trim()}>{sending ? "Sending…" : "Send"}</button><button type="button" className="secondary" onClick={onClose}>Cancel</button></div></form></dialog>;
}

export default function MessagesPage({ shopMode = false }: { shopMode?: boolean }) {
  const navigate = useNavigate(); const [rows, setRows] = useState<ShopConversation[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [compose, setCompose] = useState(false);
  const [filter, setFilter] = useState("OPEN"); const [shopId, setShopId] = useState(""); const [shops, setShops] = useState<Array<{ id: string; name: string }>>([]); const [access, setAccess] = useState<ShopAccessSnapshot | null>(null);
  useEffect(() => { if (!shopMode) return; void Promise.all([getMyShops(), getMyShopAccess()]).then(([value, snapshot]) => { setShops(value); setAccess(snapshot); setShopId((current) => current || value[0]?.id || ""); }).catch((cause) => { setShops([]); setError(cause instanceof Error ? cause.message : "Could not load shop access."); }); }, [shopMode]);
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(null); const task = shopMode ? listShopConversations(shopId || undefined, filter, controller.signal) : listSellerConversations(filter, controller.signal); void task.then((value) => setRows(value.conversations)).catch((cause) => { if (!(cause instanceof DOMException && cause.name === "AbortError")) setError(cause instanceof Error ? cause.message : "Could not load messages."); }).finally(() => setLoading(false)); return () => controller.abort(); }, [shopMode, shopId, filter]);
  const canCompose = shopMode && shops.some((shop) => shopHasPermission(access, shop.id, "messages:write"));
  return <main className="messaging-page"><section className="messaging-panel"><div className="messages-title"><h1>{shopMode ? "Shop Messages" : "Messages"}</h1><div className="messaging-actions">{!shopMode ? <><Link to="/shops">Find pawnshops</Link><Link to="/buyer/messaging-profile">Settings</Link></> : null}{canCompose ? <button className="compose-button" onClick={() => setCompose(true)}>Compose message</button> : null}</div></div><div className="messaging-filters">{shopMode ? <label>Shop<select value={shopId} onChange={(e) => setShopId(e.target.value)}>{shops.map((shop) => <option value={shop.id} key={shop.id}>{shop.name}</option>)}</select></label> : null}<label>Inbox filter<select value={filter} onChange={(e) => setFilter(e.target.value)}><option value="OPEN">Open</option><option value="CLOSED">Closed</option><option value="UNREAD">Unread</option><option value="ALL">All</option>{!shopMode ? <option value="BLOCKED">Blocked shops</option> : null}</select></label></div>{!shopMode ? <p>Your private pawnshop conversations. Your email is never shown in messages or recipient search.</p> : null}{loading ? <p role="status">Loading conversations…</p> : error ? <p role="alert" className="messaging-error">{error}</p> : rows.length === 0 ? <div className="messaging-empty"><h2>No conversations yet</h2><p>{shopMode ? "No conversations yet. Start a conversation or wait for a customer to contact your shop." : "Find a pawnshop and start a private conversation."}</p>{canCompose ? <button className="compose-button" onClick={() => setCompose(true)}>Compose message</button> : !shopMode ? <Link to="/shops">Find pawnshops</Link> : null}</div> : <div className="conversation-list">{rows.map((row) => { const last = row.messages.at(-1); const sentByShop = Boolean(last?.systemMetadata?.sentByShopId); const unread = Boolean(last && (shopMode ? !sentByShop : sentByShop) && !last.readAt); const context = row.buyerItemSubmission?.title || row.marketplaceListing?.title || row.item?.title || (row.offer ? `Offer ${row.offer.status.toLowerCase()}` : row.contactReason.replaceAll("_", " ")); return <Link key={row.id} to={`${shopMode ? "/owner/messages" : "/messages"}/${row.id}`} className="conversation-row"><div><strong>{shopMode ? row.recipientShop?.name || row.seller.publicDisplayName || row.seller.name : row.shop.name}</strong><span>{row.subject}</span><small className="conversation-context">{context}</small><small>{sentByShop && shopMode ? "Sent by your shop · " : ""}{last?.body || "No messages"}</small></div><div><span className={`message-status status-${row.status.toLowerCase()}`}>{row.status}</span>{unread ? <b className="unread-badge">Unread</b> : null}</div></Link>; })}</div>}</section>{compose ? <ComposeDialog shops={shops} access={access} initialShopId={shopId} onClose={() => setCompose(false)} onSent={(row) => { setRows((current) => [row, ...current.filter((item) => item.id !== row.id)]); setCompose(false); navigate(`/owner/messages/${row.id}`); }} /> : null}</main>;
}
