import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { getMyShops } from "../services/shops";
import { listSellerConversations, listShopConversations, type ShopConversation } from "../services/shopMessaging";
import "../styles/shop-messaging.css";

export default function MessagesPage({ shopMode = false }: { shopMode?: boolean }) {
  const [rows, setRows] = useState<ShopConversation[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [filter, setFilter] = useState("OPEN"); const [shopId, setShopId] = useState(""); const [shops, setShops] = useState<Array<{ id: string; name: string }>>([]);
  useEffect(() => { if (!shopMode) return; void getMyShops().then((value) => { setShops(value); setShopId((current) => current || value[0]?.id || ""); }).catch(() => setShops([])); }, [shopMode]);
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(null); const task = shopMode ? listShopConversations(shopId || undefined, filter, controller.signal) : listSellerConversations(controller.signal); void task.then((value) => setRows(value.conversations)).catch((cause) => { if (!(cause instanceof DOMException && cause.name === "AbortError")) setError(cause instanceof Error ? cause.message : "Could not load messages."); }).finally(() => setLoading(false)); return () => controller.abort(); }, [shopMode, shopId, filter]);
  return <main className="messaging-page"><section className="messaging-panel"><h1>{shopMode ? "Shop Messages" : "Messages"}</h1>{shopMode ? <div className="messaging-filters"><label>Shop<select value={shopId} onChange={(e) => setShopId(e.target.value)}>{shops.map((shop) => <option value={shop.id} key={shop.id}>{shop.name}</option>)}</select></label><label>Inbox filter<select value={filter} onChange={(e) => setFilter(e.target.value)}><option value="OPEN">Open</option><option value="UNREAD">Unread</option><option value="CLOSED">Closed</option><option value="ALL">All</option></select></label></div> : <p>Your private pawnshop conversations.</p>}{loading ? <p role="status">Loading conversations…</p> : error ? <p role="alert" className="messaging-error">{error}</p> : rows.length === 0 ? <div className="messaging-empty"><h2>No conversations here</h2><p>{shopMode ? "New seller messages will appear here." : "Find a pawnshop and start a private conversation."}</p>{!shopMode ? <Link to="/shops">Find pawnshops</Link> : null}</div> : <div className="conversation-list">{rows.map((row) => { const last = row.messages.at(-1); const unread = Boolean(last && last.senderUserId !== (shopMode ? "" : row.sellerUserId) && !last.readAt); return <Link key={row.id} to={`${shopMode ? "/owner/messages" : "/messages"}/${row.id}`} className="conversation-row"><div><strong>{shopMode ? row.seller.name : row.shop.name}</strong><span>{row.subject}</span><small>{last?.body || "No messages"}</small></div><div><span className={`message-status status-${row.status.toLowerCase()}`}>{row.status}</span>{unread ? <b className="unread-badge">Unread</b> : null}</div></Link>; })}</div>}</section></main>;
}
