import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { getMyShops, type Shop } from "../services/shops";
import { getBusinessGrowth, type BusinessGrowth } from "../services/businessGrowth";

const title = (value: string) => value.replace(/([A-Z])/g, " $1").replace(/^./, (letter) => letter.toUpperCase());
const money = (cents: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(cents / 100);

export default function OwnerBusinessGrowthPage() {
  const [shops, setShops] = useState<Shop[]>([]); const [shopId, setShopId] = useState("");
  const [growth, setGrowth] = useState<BusinessGrowth | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load(id: string, signal?: AbortSignal) { setLoading(true); setError(""); try { setGrowth(await getBusinessGrowth(id, signal)); } catch (cause) { if ((cause as Error)?.name !== "AbortError") setError(cause instanceof Error ? cause.message : "Unable to load Business Growth."); } finally { setLoading(false); } }
  useEffect(() => { const controller = new AbortController(); getMyShops(controller.signal).then((rows) => { setShops(rows); const id = rows[0]?.id || ""; setShopId(id); if (id) return load(id, controller.signal); setLoading(false); }).catch((cause) => { if (cause?.name !== "AbortError") setError(cause instanceof Error ? cause.message : "Unable to load shops."); setLoading(false); }); return () => controller.abort(); }, []);
  return <main style={{ maxWidth: 1200, margin: "0 auto", padding: "28px 20px 64px" }}>
    <header><p style={{ fontWeight: 800, color: "#0f766e" }}>OWNER TOOLS</p><h1>Business Growth</h1><p>Explainable operational guidance from your shop’s real PawnLoop activity.</p></header>
    {shops.length > 1 ? <label>Shop <select value={shopId} onChange={(event) => { setShopId(event.target.value); void load(event.target.value); }}>{shops.map((shop) => <option key={shop.id} value={shop.id}>{shop.name}</option>)}</select></label> : null}
    {loading ? <p aria-live="polite">Loading business growth…</p> : null}
    {error ? <section role="alert" className="list-card"><h2>Business Growth unavailable</h2><p>{error}</p><button className="button" onClick={() => shopId && void load(shopId)}>Try again</button></section> : null}
    {!loading && !error && shops.length === 0 ? <section className="list-card"><h2>No shop is available</h2><p>Create a shop before using Business Growth.</p><Link className="button" to="/owner/shops/new">Create shop</Link></section> : null}
    {growth ? <div style={{ display: "grid", gap: 18, marginTop: 20 }}>
      <section className="list-card"><h2>Growth overview</h2><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(150px,1fr))", gap: 12 }}>{Object.entries(growth.overview).map(([key, value]) => <div key={key}><strong style={{ fontSize: 24 }}>{value}</strong><div>{title(key)}</div></div>)}</div></section>
      <section className="list-card"><h2>Shop Health: {growth.health.score} / {growth.health.maximum}</h2><p>{growth.health.disclaimer} Calculation: {growth.health.calculationVersion}</p><div style={{ display: "grid", gap: 12 }}>{growth.health.components.map((component) => <article key={component.id}><h3>{component.label}: {component.score} / {component.maximum}</h3><ul>{component.checks.map((entry) => <li key={entry.id}>{entry.complete ? "✓" : "○"} {entry.label}: {entry.evidence}{entry.recommendedAction ? ` — ${entry.recommendedAction}` : ""}</li>)}</ul></article>)}</div></section>
      <section className="list-card"><h2>Marketing setup</h2><ul>{growth.marketingChecklist.map((entry) => <li key={entry.id}>{entry.complete ? "✓" : "○"} <Link to={entry.route}>{entry.label}</Link></li>)}</ul></section>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(280px,1fr))", gap: 18 }}><section className="list-card"><h2>Inventory insights</h2><dl>{Object.entries(growth.inventoryInsights).map(([key, value]) => <div key={key}><dt>{title(key)}</dt><dd>{value}</dd></div>)}</dl></section><section className="list-card"><h2>Customer insights</h2><p>Privacy-conscious aggregate counts only.</p><dl>{Object.entries(growth.customerInsights).filter(([, value]) => typeof value === "number").map(([key, value]) => <div key={key}><dt>{title(key)}</dt><dd>{String(value)}</dd></div>)}</dl><p>Reviews are unavailable because no authoritative review model exists.</p></section></div>
      <section className="list-card"><h2>Revenue summary</h2><p>{growth.revenueSummary.completedSales} completed sales · {money(growth.revenueSummary.grossSalesCents)} gross sales · {money(growth.revenueSummary.platformFeesCents)} platform fees</p><p>{growth.revenueSummary.note}</p></section>
      <section className="list-card"><h2>Marketplace Intelligence</h2><p>Aggregate shop-scoped data only · {growth.marketplaceIntelligence.access.level} access</p>{growth.marketplaceIntelligence.access.planLimited ? <p>{growth.marketplaceIntelligence.access.limitation}</p> : null}<div className="grid-2"><div><h3>Inventory</h3>{Object.entries(growth.marketplaceIntelligence.inventory).map(([key, value]) => <p key={key}>{title(key)}: {value ?? "Unavailable"}</p>)}</div><div><h3>Completed sales</h3>{Object.entries(growth.marketplaceIntelligence.sales).map(([key, value]) => <p key={key}>{title(key)}: {key.toLowerCase().includes("price") && typeof value === "number" ? money(value) : value ?? "Unavailable"}</p>)}</div></div><h3>Category performance</h3>{growth.marketplaceIntelligence.categoryPerformance.length ? <div style={{ overflowX: "auto" }}><table><thead><tr><th>Category</th><th>Active</th><th>Completed</th></tr></thead><tbody>{growth.marketplaceIntelligence.categoryPerformance.map((row) => <tr key={String(row.category)}><td>{String(row.category)}</td><td>{String(row.activeListings)}</td><td>{String(row.completedSales)}</td></tr>)}</tbody></table></div> : <p>Insufficient category activity.</p>}<p><small>{growth.marketplaceIntelligence.limitations.join(" ")}</small></p></section>
      <section className="list-card"><h2>Growth opportunities</h2>{growth.opportunities.filter((item) => !item.complete).length ? <div style={{ display: "grid", gap: 10 }}>{growth.opportunities.filter((item) => !item.complete).map((item) => <article key={item.id}><strong>{item.priority}: {item.action}</strong><p>{item.reason}</p><Link to={item.route}>Take action</Link></article>)}</div> : <p>No current rule-based opportunities. Keep monitoring this page as activity changes.</p>}</section>
      <section className="list-card"><h2>Business Coach V1</h2><p>Rule-based guidance ({growth.businessCoach.calculationVersion}); no generative AI is used.</p>{growth.businessCoach.recommendations.map((item, index) => <p key={`${item.route}-${index}`}>{item.statement} <Link to={item.route}>{item.action}</Link></p>)}</section>
      <section className="list-card"><h2>Plan usage — {growth.planUsage.displayName}</h2><p>Internal plan: {growth.planUsage.sellerPlan} · Status: {growth.planUsage.status} · Commission: {(growth.planUsage.commission.commissionBps / 100).toFixed(2)}%</p>{Object.entries(growth.planUsage.usage).map(([key, value]) => <p key={key}>{title(key)}: {value.used} / {value.unlimited ? "Unlimited" : value.limit}</p>)}<p>Implemented: {growth.planUsage.implementation.implemented.join(", ")}</p><p>Planned eligibility (not implemented): {growth.planUsage.implementation.planned.join(", ")}</p></section>
    </div> : null}
  </main>;
}
