import { useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { paymentMethodsApi, type SafePaymentMethod } from "../services/paymentMethods";

const isStripeHost = (hostname: string) => hostname === "stripe.com" || hostname.endsWith(".stripe.com");

export default function PaymentMethodsPage() {
  const [params] = useSearchParams(); const shopId = params.get("shopId");
  const [methods, setMethods] = useState<SafePaymentMethod[]>([]); const [sync, setSync] = useState("UNKNOWN");
  const [consent, setConsent] = useState(false); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  async function load() { setLoading(true); setError(""); try { const result = await paymentMethodsApi.list(shopId); setMethods(result.methods); setSync(result.syncStatus); if (params.get("setup") === "complete") setNotice("Stripe setup completed. Your saved methods have been synchronized."); else if (params.get("setup") === "canceled") setNotice("Stripe setup was canceled. No payment method was changed."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load payment methods."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [shopId]); // eslint-disable-line react-hooks/exhaustive-deps
  async function setup() { if (!consent) { setError("Consent is required before saving a method for future charges."); return; } setBusy(true); setError(""); try { const success = new URL(location.href); success.searchParams.set("setup", "complete"); const cancel = new URL(location.href); cancel.searchParams.set("setup", "canceled"); const result = await paymentMethodsApi.setup({ shopId, successUrl: success.toString(), cancelUrl: cancel.toString(), consent: { accepted: true, termsVersion: "payment-method-consent-v1" } }); const target = new URL(result.url); if (target.protocol !== "https:" || !isStripeHost(target.hostname)) throw new Error("Stripe returned an untrusted setup URL."); location.assign(target.toString()); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to start secure setup."); setBusy(false); } }
  async function makeDefault(id: string) { setBusy(true); try { const result = await paymentMethodsApi.setDefault(id, shopId); setMethods(result.methods); setNotice("Default payment method updated."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to update the default method."); } finally { setBusy(false); } }
  async function remove(id: string) { if (!confirm("Remove this saved payment method? Active subscriptions must retain an eligible method.")) return; setBusy(true); try { const result = await paymentMethodsApi.remove(id, shopId); setMethods(result.methods); setNotice("Payment method removed from Stripe."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to remove the method."); } finally { setBusy(false); } }
  async function portal() { setBusy(true); try { const result = await paymentMethodsApi.portal(shopId, location.href); const target = new URL(result.url); if (target.protocol !== "https:" || !isStripeHost(target.hostname)) throw new Error("Stripe returned an untrusted portal URL."); location.assign(target.toString()); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to open Stripe billing."); setBusy(false); } }
  return <main className="mx-auto w-full max-w-5xl space-y-6 px-4 py-8"><header className="rounded-2xl border bg-background p-6"><div className="text-xs font-bold uppercase tracking-wider text-muted-foreground">{shopId ? "Seller billing" : "Buyer wallet"}</div><h1 className="text-3xl font-bold">Payment Methods</h1><p className="mt-2 text-sm text-muted-foreground">Card and bank details are collected and stored by Stripe. PawnLoop receives only Stripe references and masked display details.</p><div className="mt-4 flex flex-wrap gap-2"><button className="btn btn-primary" disabled={busy} onClick={() => void setup()}>{busy ? "Opening Stripe…" : "Add or replace payment method"}</button><button className="btn btn-secondary" disabled={busy} onClick={() => void portal()}>Open Stripe billing portal</button>{shopId ? <><Link className="btn btn-secondary" to={`/owner/finance?shopId=${encodeURIComponent(shopId)}`}>Payout account</Link><Link className="btn btn-secondary" to="/owner/subscription">Seller plan</Link></> : null}</div></header>
    <label className="flex items-start gap-3 rounded-2xl border bg-background p-4 text-sm"><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} className="mt-1 h-4 w-4 focus-visible:ring-2 focus-visible:ring-blue-600" /><span>I authorize PawnLoop and Stripe to store this payment method and use it for future or off-session charges that I authorize. Consent time and mandate references will be retained.</span></label>
    {error && <div role="alert" className="rounded-xl border border-red-300 bg-red-50 p-4 text-red-800">{error}</div>}{notice && <div role="status" className="rounded-xl border border-green-300 bg-green-50 p-4 text-green-800">{notice}</div>}
    <section className="rounded-2xl border bg-background p-5"><div className="flex justify-between"><h2 className="text-xl font-bold">Saved methods</h2><span className="text-sm text-muted-foreground">Stripe sync: {sync}</span></div>{loading ? <p className="py-8 text-center">Loading masked payment methods…</p> : methods.length === 0 ? <p className="py-8 text-center text-muted-foreground">No payment methods saved. Add one securely through Stripe.</p> : <div className="mt-4 grid gap-3">{methods.map((method) => <article key={method.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-4"><div><strong>{method.brand || method.type} •••• {method.last4 || "unknown"}</strong><div className="text-sm text-muted-foreground">{method.expMonth ? `Expires ${method.expMonth}/${method.expYear}` : method.type} · {method.status}{method.default ? " · Default" : ""}</div></div><div className="flex gap-2">{!method.default && <button className="btn btn-secondary" disabled={busy || method.expired} onClick={() => void makeDefault(method.id)}>Set default</button>}<button className="btn btn-secondary" disabled={busy} onClick={() => void setup()}>Update</button><button className="btn btn-secondary" disabled={busy} onClick={() => void remove(method.id)}>Remove</button></div></article>)}</div>}</section>
  </main>;
}
