import { useEffect, useRef, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { paymentMethodsApi, type SafePaymentMethod } from "../services/paymentMethods";
import "../styles/buyer-account.css";

const isStripeHost = (hostname: string) => hostname === "stripe.com" || hostname.endsWith(".stripe.com");

export default function PaymentMethodsPage() {
  const [params] = useSearchParams(); const shopId = params.get("shopId");
  const [methods, setMethods] = useState<SafePaymentMethod[]>([]); const [sync, setSync] = useState("UNKNOWN");
  const [consent, setConsent] = useState(false);
  const consentRef = useRef<HTMLInputElement>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  async function load() { setLoading(true); setError(""); try { const result = await paymentMethodsApi.list(shopId); setMethods(result.methods); setSync(result.syncStatus); if (params.get("setup") === "complete") setNotice("Stripe setup completed. Your saved methods have been synchronized."); else if (params.get("setup") === "canceled") setNotice("Stripe setup was canceled. No payment method was changed."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load payment methods."); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [shopId]); // eslint-disable-line react-hooks/exhaustive-deps
  async function setup() { if (!consent) { setNotice(""); setError("Review and accept the payment-method consent before continuing to Stripe."); requestAnimationFrame(() => { consentRef.current?.focus(); consentRef.current?.scrollIntoView({ behavior: "smooth", block: "center" }); }); return; } setBusy(true); setError(""); try { const success = new URL(location.href); success.searchParams.set("setup", "complete"); const cancel = new URL(location.href); cancel.searchParams.set("setup", "canceled"); const result = await paymentMethodsApi.setup({ shopId, successUrl: success.toString(), cancelUrl: cancel.toString(), consent: { accepted: true, termsVersion: "payment-method-consent-v1" } }); const target = new URL(result.url); if (target.protocol !== "https:" || !isStripeHost(target.hostname)) throw new Error("Stripe returned an untrusted setup URL."); location.assign(target.toString()); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to start secure setup."); setBusy(false); } }
  async function makeDefault(id: string) { setBusy(true); try { const result = await paymentMethodsApi.setDefault(id, shopId); setMethods(result.methods); setNotice("Default payment method updated."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to update the default method."); } finally { setBusy(false); } }
  async function remove(id: string) { if (!confirm("Remove this saved payment method? Active subscriptions must retain an eligible method.")) return; setBusy(true); try { const result = await paymentMethodsApi.remove(id, shopId); setMethods(result.methods); setNotice("Payment method removed from Stripe."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to remove the method."); } finally { setBusy(false); } }
  async function portal() { setBusy(true); try { const result = await paymentMethodsApi.portal(shopId, location.href); const target = new URL(result.url); if (target.protocol !== "https:" || !isStripeHost(target.hostname)) throw new Error("Stripe returned an untrusted portal URL."); location.assign(target.toString()); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to open Stripe billing."); setBusy(false); } }
  return <main className="payment-methods-page"><header className="payment-methods-hero"><div className="payment-methods-kicker">{shopId ? "Seller billing" : "Buyer wallet"}</div><h1>Payment Methods</h1><p className="payment-methods-intro">Card and bank details are collected and stored by Stripe. PawnLoop receives only Stripe references and masked display details.</p><div className="payment-methods-actions"><button className="btn btn-primary" aria-describedby="payment-method-consent-copy" disabled={busy} onClick={() => void setup()}>{busy ? "Opening Stripe…" : "Add or replace payment method"}</button><button className="btn btn-secondary" disabled={busy} onClick={() => void portal()}>Open Stripe billing portal</button>{shopId ? <><Link className="btn btn-secondary" to={`/owner/finance?shopId=${encodeURIComponent(shopId)}`}>Payout account</Link><Link className="btn btn-secondary" to="/owner/subscription">Seller plan</Link></> : null}</div></header>
    <label className="payment-methods-consent"><input ref={consentRef} type="checkbox" checked={consent} aria-describedby="payment-method-consent-copy" onChange={(event) => { const nextConsent = event.target.checked; setConsent(nextConsent); if (nextConsent) setError(""); }} className="payment-methods-consent-checkbox" /><span id="payment-method-consent-copy" className="payment-methods-consent-copy">I authorize PawnLoop and Stripe to store this payment method and use it for future or off-session charges that I authorize. Consent time and mandate references will be retained.</span></label>
    {error && <div role="alert" className="payment-methods-alert payment-methods-alert-error">{error}</div>}{notice && <div role="status" className="payment-methods-alert payment-methods-alert-success">{notice}</div>}
    <section className="payment-methods-card"><div className="payment-methods-section-header"><h2>Saved methods</h2><span className="payment-methods-sync">Stripe sync: {sync}</span></div>{loading ? <p className="payment-methods-empty">Loading masked payment methods…</p> : methods.length === 0 ? <p className="payment-methods-empty">No payment methods saved. Add one securely through Stripe.</p> : <div className="payment-methods-list">{methods.map((method) => <article key={method.id} className="payment-methods-method"><div className="payment-methods-method-copy"><strong>{method.brand || method.type} •••• {method.last4 || "unknown"}</strong><div className="payment-methods-method-meta">{method.expMonth ? `Expires ${method.expMonth}/${method.expYear}` : method.type} · {method.status}{method.default ? " · Default" : ""}</div></div><div className="payment-methods-method-actions">{!method.default && <button className="btn btn-secondary" disabled={busy || method.expired} onClick={() => void makeDefault(method.id)}>Set default</button>}<button className="btn btn-secondary" disabled={busy} onClick={() => void setup()}>Update</button><button className="btn btn-secondary" disabled={busy} onClick={() => void remove(method.id)}>Remove</button></div></article>)}</div>}</section>
  </main>;
}
