import { useEffect, useMemo, useState, type FormEvent } from "react";
import { useNavigate, useParams } from "react-router-dom";
import AdminPageShell from "../admin/components/AdminPageShell";
import { adminApi, type AdminShopRow, type InventorySupportEvent, type InventorySupportLocation, type InventorySupportSession, type SupportInventoryItem } from "../admin/services/adminApi";
import { uploadItemImages } from "../services/uploads";

const STATES = ["AVAILABLE", "RESERVED", "SOLD", "PAWNED", "LAYAWAY", "UNAVAILABLE", "ARCHIVED"];
const empty = { title: "", description: "", sku: "", barcode: "", serialNumber: "", category: "", condition: "", quantity: "1", price: "0", cost: "", locationId: "", availability: "AVAILABLE", images: "", reason: "" };

export default function SuperAdminShopSupportPage() {
  const { shopId = "" } = useParams(); const navigate = useNavigate();
  const [shop, setShop] = useState<AdminShopRow | null>(null); const [session, setSession] = useState<InventorySupportSession | null>(null);
  const [entryReason, setEntryReason] = useState(""); const [query, setQuery] = useState(""); const [items, setItems] = useState<SupportInventoryItem[]>([]);
  const [form, setForm] = useState(empty); const [editing, setEditing] = useState<SupportInventoryItem | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const [loading, setLoading] = useState(false); const [locations, setLocations] = useState<InventorySupportLocation[]>([]); const [history, setHistory] = useState<InventorySupportEvent[]>([]);
  const [locationName, setLocationName] = useState(""); const [locationReason, setLocationReason] = useState("");
  const [imageFiles, setImageFiles] = useState<File[]>([]);
  const storageKey = `inventory-support:${shopId}`;
  useEffect(() => { const raw = sessionStorage.getItem(storageKey); if (raw) { try { const saved = JSON.parse(raw); setSession(saved.session); setShop(saved.shop); } catch { sessionStorage.removeItem(storageKey); } } }, [storageKey]);
  useEffect(() => { if (!session) return; let active = true; setLoading(true); setError(""); Promise.all([adminApi.getSupportInventory(shopId, session.id, query), adminApi.getSupportLocations(shopId, session.id), adminApi.getSupportHistory(shopId, session.id)]).then(([inventory, locationResult, historyResult]) => { if (!active) return; setItems(inventory.items); setLocations(locationResult.locations); setHistory(historyResult.events); }).catch((e) => { if (!active) return; const message = e instanceof Error ? e.message : "Unable to load inventory support data."; if (/support session is invalid, ended, or belongs/i.test(message)) { sessionStorage.removeItem(storageKey); setSession(null); setShop(null); setError("The support session expired or ended. Enter support mode again."); return; } setError(message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [shopId, session, query, storageKey]);
  const shown = useMemo(() => items, [items]);
  async function enter(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const result = await adminApi.startInventorySupport(shopId, entryReason); setSession(result.session); setShop(result.shop); sessionStorage.setItem(storageKey, JSON.stringify(result)); } catch (e) { setError(e instanceof Error ? e.message : "Unable to enter support mode."); } finally { setBusy(false); } }
  async function exit() { if (!session) return; setBusy(true); try { await adminApi.endInventorySupport(shopId, session.id, "Administrator explicitly exited support mode"); sessionStorage.removeItem(storageKey); navigate("/super-admin/shops"); } catch (e) { setError(e instanceof Error ? e.message : "Unable to exit support mode."); setBusy(false); } }
  function edit(item: SupportInventoryItem) { setEditing(item); setImageFiles([]); setForm({ title: item.title || "", description: item.description || "", sku: item.sku || "", barcode: item.barcode || "", serialNumber: item.serialNumber || "", category: item.category || "", condition: item.condition || "", quantity: String(item.quantity), price: String(item.price ?? 0), cost: item.cost == null ? "" : String(item.cost), locationId: item.locationId || "", availability: item.availability || "AVAILABLE", images: (item.images || []).join("\n"), reason: "" }); }
  async function save(event: FormEvent) { event.preventDefault(); if (!session) return; setBusy(true); setError(""); try { const uploaded = editing && imageFiles.length ? await uploadItemImages(editing.id, imageFiles) : []; const images = [...form.images.split("\n").map((x) => x.trim()).filter(Boolean), ...uploaded.map((file) => file.url)]; const input: Record<string, unknown> = { ...form, quantity: Number(form.quantity), price: Number(form.price), cost: form.cost === "" ? null : Number(form.cost), images }; if (editing) { const original: Record<string, unknown> = { title: editing.title || "", description: editing.description || "", sku: editing.sku || "", barcode: editing.barcode || "", serialNumber: editing.serialNumber || "", category: editing.category || "", condition: editing.condition || "", quantity: Number(editing.quantity), price: Number(editing.price ?? 0), cost: editing.cost == null ? null : Number(editing.cost), locationId: editing.locationId || "", availability: editing.availability || "AVAILABLE", images: editing.images || [] }; for (const key of Object.keys(original)) if (JSON.stringify(input[key]) === JSON.stringify(original[key])) delete input[key]; if (Object.keys(input).every((key) => key === "reason")) throw new Error("Change at least one inventory field before saving."); await adminApi.updateSupportInventory(shopId, editing.id, session.id, input); } else { delete input.images; await adminApi.createSupportInventory(shopId, session.id, input); } const result = await adminApi.getSupportInventory(shopId, session.id, query); setItems(result.items); setEditing(null); setImageFiles([]); setForm(empty); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save inventory."); } finally { setBusy(false); } }
  async function listing(item: SupportInventoryItem, action: string) { if (!session) return; const why = window.prompt(`Reason for ${action} listing`); if (!why) return; try { await adminApi.changeSupportListing(shopId, item.id, session.id, action, why); const result = await adminApi.getSupportInventory(shopId, session.id, query); setItems(result.items); } catch (e) { setError(e instanceof Error ? e.message : "Listing change failed."); } }
  async function createLocation(event: FormEvent) { event.preventDefault(); if (!session) return; setBusy(true); setError(""); try { const result = await adminApi.createSupportLocation(shopId, session.id, locationName, locationReason); setLocations((current) => [...current, result.location].sort((a, b) => a.name.localeCompare(b.name))); setLocationName(""); setLocationReason(""); } catch (e) { setError(e instanceof Error ? e.message : "Unable to create location."); } finally { setBusy(false); } }
  if (!session) return <AdminPageShell title="Manage shop inventory" subtitle="Enter explicit support mode; this does not impersonate the owner or staff.">{error && <div className="admin-notice danger">{error}</div>}<form className="page-card" onSubmit={enter}><h2>Enter Super Admin support mode</h2><label>Required support reason<textarea value={entryReason} onChange={(e) => setEntryReason(e.target.value)} minLength={8} required rows={4} className="admin-control-input" /></label><button className="btn btn-primary" disabled={busy}>{busy ? "Entering…" : "Enter support mode"}</button></form></AdminPageShell>;
  return <AdminPageShell title={`Manage ${shop?.name || "shop"}`} subtitle="Audited inventory support workspace">
    <div role="status" style={{ position: "sticky", top: 0, zIndex: 20, display: "flex", justifyContent: "space-between", gap: 12, flexWrap: "wrap", padding: 16, background: "#7c2d12", color: "white", borderRadius: 10 }}><strong>Super Admin support mode · {shop?.name || shopId}</strong><button className="btn btn-secondary" onClick={() => void exit()} disabled={busy}>Exit</button></div>
    {error && <div className="admin-notice danger" role="alert"><strong>{/forbidden|permission|super admin/i.test(error) ? "Permission denied. " : /conflict|active auction|offer|reservation|purchase|fulfillment|lifecycle/i.test(error) ? "Inventory conflict. " : ""}</strong>{error}</div>}
    <input aria-label="Search inventory" className="admin-control-input" placeholder="Search name, SKU, barcode, serial, category or condition" value={query} onChange={(e) => setQuery(e.target.value)} />
    <form className="page-card" onSubmit={createLocation}><h2>Create inventory location</h2><div style={{ display: "flex", gap: 12, flexWrap: "wrap" }}><label>Location name<input className="admin-control-input" value={locationName} onChange={(e) => setLocationName(e.target.value)} required /></label><label>Support reason<input className="admin-control-input" value={locationReason} onChange={(e) => setLocationReason(e.target.value)} minLength={8} required /></label><button className="btn btn-secondary" disabled={busy}>Create location</button></div></form>
    <form className="page-card" onSubmit={save}><h2>{editing ? `Edit ${editing.title}` : "Create inventory"}</h2><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(180px,1fr))", gap: 12 }}>{["title", "sku", "barcode", "serialNumber", "category", "condition", "quantity", "price", "cost"].map((key) => <label key={key}>{key}<input className="admin-control-input" type={["quantity", "price", "cost"].includes(key) ? "number" : "text"} min={["quantity", "price", "cost"].includes(key) ? 0 : undefined} step={["price", "cost"].includes(key) ? ".01" : undefined} value={form[key as keyof typeof form]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} required={key === "title"} /></label>)}<label>location<select className="admin-control-select" value={form.locationId} onChange={(e) => setForm({ ...form, locationId: e.target.value })}><option value="">Unassigned</option>{locations.map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</select></label><label>availability<select className="admin-control-select" value={form.availability} onChange={(e) => setForm({ ...form, availability: e.target.value })}>{STATES.map((s) => <option key={s}>{s}</option>)}</select></label></div><label>Description<textarea className="admin-control-input" rows={3} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><label>Attached managed images<textarea className="admin-control-input" rows={3} value={form.images} readOnly /></label>{editing ? <><label>Add managed images<input key={imageFiles.length ? imageFiles.map((file) => file.name).join(":") : "empty"} className="admin-control-input" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={(e) => setImageFiles(Array.from(e.target.files || []))} /></label><button type="button" className="btn btn-secondary" onClick={() => { setImageFiles([]); setForm({ ...form, images: "" }); }}>Remove all images</button></> : <p className="admin-muted">Create the item first, then edit it to upload managed images.</p>}<label>Reason for this mutation<textarea className="admin-control-input" minLength={8} required value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value })} /></label><div style={{ display: "flex", gap: 8 }}><button className="btn btn-primary" disabled={busy}>Save</button>{editing && <button type="button" className="btn btn-secondary" onClick={() => { setEditing(null); setImageFiles([]); setForm(empty); }}>Cancel</button>}</div></form>
    {loading ? <div className="page-card" role="status">Loading inventory support data…</div> : shown.length === 0 ? <div className="page-card">No inventory matches this shop-scoped search.</div> :
    <div className="admin-table-card"><div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>Item</th><th>Identifiers</th><th>Quantity</th><th>Availability</th><th>Listing</th><th>Actions</th></tr></thead><tbody>{shown.map((item) => <tr key={item.id}><td><strong>{item.title}</strong><div className="admin-muted">{item.category || "—"} · {item.condition || "—"}</div></td><td>{item.sku || item.barcode || item.serialNumber || "—"}</td><td>{item.quantity}</td><td>{item.availability}</td><td>{item.marketplaceListings?.[0]?.status || "Unlisted"}</td><td><div className="super-admin-row-actions"><button className="btn btn-secondary" onClick={() => edit(item)}>Edit</button>{["publish", "unpublish", "archive", "restore"].map((a) => <button key={a} className="btn btn-secondary" onClick={() => void listing(item, a)}>{a}</button>)}</div></td></tr>)}</tbody></table></div></div>
    }
    <section className="page-card"><h2>Administrative inventory history</h2>{history.length === 0 ? <p>No administrative inventory changes have been recorded for this shop.</p> : <div className="admin-table-scroll"><table className="admin-table"><thead><tr><th>When</th><th>Action</th><th>Reason</th><th>Request ID</th></tr></thead><tbody>{history.map((event) => <tr key={event.id}><td>{new Date(event.createdAt).toLocaleString()}</td><td>{event.action}</td><td>{event.reason}</td><td><code>{event.requestId || "—"}</code></td></tr>)}</tbody></table></div>}</section>
  </AdminPageShell>;
}
